/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api;

import com.shutterstock.api.authentication.BasicCredentials;
import com.shutterstock.api.authentication.BasicModel;
import com.shutterstock.api.authentication.CustomerAccessCodeCredentials;
import com.shutterstock.api.authentication.CustomerAccessCodeModel;
import com.shutterstock.api.http.client.ReadonlyHttpClientConfiguration;
import com.shutterstock.api.logging.configuration.ReadonlyLoggingConfiguration;

/**
 * Configuration Interface for the library.
 */
public interface Configuration {

    /**
     * Current API environment.
     * @return a copy of environment
     */
    Environment getEnvironment();

    /**
     * Http Client Configuration instance.
     * @return a copy of httpClientConfig
     */
    ReadonlyHttpClientConfiguration getHttpClientConfig();

    /**
     * Logging Configuration instance.
     * @return a copy of loggingConfig
     */
    ReadonlyLoggingConfiguration getLoggingConfig();

    /**
     * The timeout to use for making HTTP requests. The timeout to use for making HTTP requests.
     * @return a copy of timeout
     */
    long timeout();

    /**
     * The credentials to use with Basic.
     * @return basicCredentials
     */
    BasicCredentials getBasicCredentials();

    /**
     * The auth credential model for Basic.
     * @return the instance of BasicModel
     */
    BasicModel getBasicModel();

    /**
     * The credentials to use with CustomerAccessCode.
     * @return customerAccessCodeCredentials
     */
    CustomerAccessCodeCredentials getCustomerAccessCodeCredentials();

    /**
     * The auth credential model for CustomerAccessCode.
     * @return the instance of CustomerAccessCodeModel
     */
    CustomerAccessCodeModel getCustomerAccessCodeModel();

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    String getBaseUri(Server server);

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    String getBaseUri();
}
