/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for Allotment type.
 */
public class Allotment {
    private Integer downloadsLeft;
    private Integer downloadsLimit;
    private LocalDateTime endTime;
    private LocalDateTime startTime;
    private Object contentTiers;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Allotment() {
    }

    /**
     * Initialization constructor.
     * @param  downloadsLeft  Integer value for downloadsLeft.
     * @param  downloadsLimit  Integer value for downloadsLimit.
     * @param  endTime  LocalDateTime value for endTime.
     * @param  startTime  LocalDateTime value for startTime.
     * @param  contentTiers  Object value for contentTiers.
     */
    public Allotment(
            Integer downloadsLeft,
            Integer downloadsLimit,
            LocalDateTime endTime,
            LocalDateTime startTime,
            Object contentTiers) {
        this.downloadsLeft = downloadsLeft;
        this.downloadsLimit = downloadsLimit;
        this.endTime = endTime;
        this.startTime = startTime;
        this.contentTiers = contentTiers;
    }

    /**
     * Getter for DownloadsLeft.
     * Number of credits remaining in the subscription
     * @return Returns the Integer
     */
    @JsonGetter("downloads_left")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDownloadsLeft() {
        return downloadsLeft;
    }

    /**
     * Setter for DownloadsLeft.
     * Number of credits remaining in the subscription
     * @param downloadsLeft Value for Integer
     */
    @JsonSetter("downloads_left")
    public void setDownloadsLeft(Integer downloadsLeft) {
        this.downloadsLeft = downloadsLeft;
    }

    /**
     * Getter for DownloadsLimit.
     * Total number of credits available to this subscription
     * @return Returns the Integer
     */
    @JsonGetter("downloads_limit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDownloadsLimit() {
        return downloadsLimit;
    }

    /**
     * Setter for DownloadsLimit.
     * Total number of credits available to this subscription
     * @param downloadsLimit Value for Integer
     */
    @JsonSetter("downloads_limit")
    public void setDownloadsLimit(Integer downloadsLimit) {
        this.downloadsLimit = downloadsLimit;
    }

    /**
     * Getter for EndTime.
     * Date the subscription ends
     * @return Returns the LocalDateTime
     */
    @JsonGetter("end_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * Setter for EndTime.
     * Date the subscription ends
     * @param endTime Value for LocalDateTime
     */
    @JsonSetter("end_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * Getter for StartTime.
     * Date the subscription started
     * @return Returns the LocalDateTime
     */
    @JsonGetter("start_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * Setter for StartTime.
     * Date the subscription started
     * @param startTime Value for LocalDateTime
     */
    @JsonSetter("start_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * Getter for ContentTiers.
     * Downloads left and limit values for each content tier in the license
     * @return Returns the Object
     */
    @JsonGetter("content_tiers")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getContentTiers() {
        return contentTiers;
    }

    /**
     * Setter for ContentTiers.
     * Downloads left and limit values for each content tier in the license
     * @param contentTiers Value for Object
     */
    @JsonSetter("content_tiers")
    public void setContentTiers(Object contentTiers) {
        this.contentTiers = contentTiers;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Allotment into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Allotment [" + "downloadsLeft=" + downloadsLeft + ", downloadsLimit="
                + downloadsLimit + ", endTime=" + endTime + ", startTime=" + startTime
                + ", contentTiers=" + contentTiers + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Allotment.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Allotment.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .downloadsLeft(getDownloadsLeft())
                .downloadsLimit(getDownloadsLimit())
                .endTime(getEndTime())
                .startTime(getStartTime())
                .contentTiers(getContentTiers());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Allotment}.
     */
    public static class Builder {
        private Integer downloadsLeft;
        private Integer downloadsLimit;
        private LocalDateTime endTime;
        private LocalDateTime startTime;
        private Object contentTiers;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for downloadsLeft.
         * @param  downloadsLeft  Integer value for downloadsLeft.
         * @return Builder
         */
        public Builder downloadsLeft(Integer downloadsLeft) {
            this.downloadsLeft = downloadsLeft;
            return this;
        }

        /**
         * Setter for downloadsLimit.
         * @param  downloadsLimit  Integer value for downloadsLimit.
         * @return Builder
         */
        public Builder downloadsLimit(Integer downloadsLimit) {
            this.downloadsLimit = downloadsLimit;
            return this;
        }

        /**
         * Setter for endTime.
         * @param  endTime  LocalDateTime value for endTime.
         * @return Builder
         */
        public Builder endTime(LocalDateTime endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * Setter for startTime.
         * @param  startTime  LocalDateTime value for startTime.
         * @return Builder
         */
        public Builder startTime(LocalDateTime startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * Setter for contentTiers.
         * @param  contentTiers  Object value for contentTiers.
         * @return Builder
         */
        public Builder contentTiers(Object contentTiers) {
            this.contentTiers = contentTiers;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Allotment} object using the set fields.
         * @return {@link Allotment}
         */
        public Allotment build() {
            Allotment model =
                    new Allotment(downloadsLeft, downloadsLimit, endTime, startTime, contentTiers);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
