/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * AspectRatio to be used.
 */
public enum AspectRatio {
    ENUM_4_3,

    ENUM_16_9,

    NONSTANDARD;

    private static TreeMap<String, AspectRatio> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_4_3.value = "4_3";
        ENUM_16_9.value = "16_9";
        NONSTANDARD.value = "nonstandard";

        valueMap.put("4_3", ENUM_4_3);
        valueMap.put("16_9", ENUM_16_9);
        valueMap.put("nonstandard", NONSTANDARD);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AspectRatio constructFromString(String toConvert) throws IOException {
        AspectRatio enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AspectRatio fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AspectRatio values to list of string values.
     * @param toConvert The list of AspectRatio values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AspectRatio> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AspectRatio enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 