/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * AudioLayout to be used.
 */
public enum AudioLayout {
    AMBISONIC,

    ENUM_51,

    STEREO;

    private static TreeMap<String, AudioLayout> valueMap = new TreeMap<>();
    private String value;

    static {
        AMBISONIC.value = "ambisonic";
        ENUM_51.value = "5.1";
        STEREO.value = "stereo";

        valueMap.put("ambisonic", AMBISONIC);
        valueMap.put("5.1", ENUM_51);
        valueMap.put("stereo", STEREO);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AudioLayout constructFromString(String toConvert) throws IOException {
        AudioLayout enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AudioLayout fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AudioLayout values to list of string values.
     * @param toConvert The list of AudioLayout values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AudioLayout> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AudioLayout enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 