/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for CatalogCollection type.
 */
public class CatalogCollection {
    private String id;
    private String name;
    private CatalogCollectionItem coverAsset;
    private double totalItemCount;
    private LocalDateTime createdTime;
    private LocalDateTime updatedTime;
    private Visibility visibility;
    private CatalogCollectionRoleAssignments roleAssignments;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CatalogCollection() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  totalItemCount  double value for totalItemCount.
     * @param  createdTime  LocalDateTime value for createdTime.
     * @param  updatedTime  LocalDateTime value for updatedTime.
     * @param  visibility  Visibility value for visibility.
     * @param  roleAssignments  CatalogCollectionRoleAssignments value for roleAssignments.
     * @param  coverAsset  CatalogCollectionItem value for coverAsset.
     */
    public CatalogCollection(
            String id,
            String name,
            double totalItemCount,
            LocalDateTime createdTime,
            LocalDateTime updatedTime,
            Visibility visibility,
            CatalogCollectionRoleAssignments roleAssignments,
            CatalogCollectionItem coverAsset) {
        this.id = id;
        this.name = name;
        this.coverAsset = coverAsset;
        this.totalItemCount = totalItemCount;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
        this.visibility = visibility;
        this.roleAssignments = roleAssignments;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for CoverAsset.
     * Metadata about an item that is part of a collection
     * @return Returns the CatalogCollectionItem
     */
    @JsonGetter("cover_asset")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CatalogCollectionItem getCoverAsset() {
        return coverAsset;
    }

    /**
     * Setter for CoverAsset.
     * Metadata about an item that is part of a collection
     * @param coverAsset Value for CatalogCollectionItem
     */
    @JsonSetter("cover_asset")
    public void setCoverAsset(CatalogCollectionItem coverAsset) {
        this.coverAsset = coverAsset;
    }

    /**
     * Getter for TotalItemCount.
     * @return Returns the double
     */
    @JsonGetter("total_item_count")
    public double getTotalItemCount() {
        return totalItemCount;
    }

    /**
     * Setter for TotalItemCount.
     * @param totalItemCount Value for double
     */
    @JsonSetter("total_item_count")
    public void setTotalItemCount(double totalItemCount) {
        this.totalItemCount = totalItemCount;
    }

    /**
     * Getter for CreatedTime.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created_time")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * Setter for CreatedTime.
     * @param createdTime Value for LocalDateTime
     */
    @JsonSetter("created_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * Getter for UpdatedTime.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("updated_time")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * Setter for UpdatedTime.
     * @param updatedTime Value for LocalDateTime
     */
    @JsonSetter("updated_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * Getter for Visibility.
     * @return Returns the Visibility
     */
    @JsonGetter("visibility")
    public Visibility getVisibility() {
        return visibility;
    }

    /**
     * Setter for Visibility.
     * @param visibility Value for Visibility
     */
    @JsonSetter("visibility")
    public void setVisibility(Visibility visibility) {
        this.visibility = visibility;
    }

    /**
     * Getter for RoleAssignments.
     * List of role assignments for a catalog collection
     * @return Returns the CatalogCollectionRoleAssignments
     */
    @JsonGetter("role_assignments")
    public CatalogCollectionRoleAssignments getRoleAssignments() {
        return roleAssignments;
    }

    /**
     * Setter for RoleAssignments.
     * List of role assignments for a catalog collection
     * @param roleAssignments Value for CatalogCollectionRoleAssignments
     */
    @JsonSetter("role_assignments")
    public void setRoleAssignments(CatalogCollectionRoleAssignments roleAssignments) {
        this.roleAssignments = roleAssignments;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CatalogCollection into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CatalogCollection [" + "id=" + id + ", name=" + name + ", totalItemCount="
                + totalItemCount + ", createdTime=" + createdTime + ", updatedTime=" + updatedTime
                + ", visibility=" + visibility + ", roleAssignments=" + roleAssignments
                + ", coverAsset=" + coverAsset + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link CatalogCollection.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CatalogCollection.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, totalItemCount, createdTime, updatedTime,
                visibility, roleAssignments)
                .coverAsset(getCoverAsset());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CatalogCollection}.
     */
    public static class Builder {
        private String id;
        private String name;
        private double totalItemCount;
        private LocalDateTime createdTime;
        private LocalDateTime updatedTime;
        private Visibility visibility;
        private CatalogCollectionRoleAssignments roleAssignments;
        private CatalogCollectionItem coverAsset;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  name  String value for name.
         * @param  totalItemCount  double value for totalItemCount.
         * @param  createdTime  LocalDateTime value for createdTime.
         * @param  updatedTime  LocalDateTime value for updatedTime.
         * @param  visibility  Visibility value for visibility.
         * @param  roleAssignments  CatalogCollectionRoleAssignments value for roleAssignments.
         */
        public Builder(String id, String name, double totalItemCount, LocalDateTime createdTime,
                LocalDateTime updatedTime, Visibility visibility,
                CatalogCollectionRoleAssignments roleAssignments) {
            this.id = id;
            this.name = name;
            this.totalItemCount = totalItemCount;
            this.createdTime = createdTime;
            this.updatedTime = updatedTime;
            this.visibility = visibility;
            this.roleAssignments = roleAssignments;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for totalItemCount.
         * @param  totalItemCount  double value for totalItemCount.
         * @return Builder
         */
        public Builder totalItemCount(double totalItemCount) {
            this.totalItemCount = totalItemCount;
            return this;
        }

        /**
         * Setter for createdTime.
         * @param  createdTime  LocalDateTime value for createdTime.
         * @return Builder
         */
        public Builder createdTime(LocalDateTime createdTime) {
            this.createdTime = createdTime;
            return this;
        }

        /**
         * Setter for updatedTime.
         * @param  updatedTime  LocalDateTime value for updatedTime.
         * @return Builder
         */
        public Builder updatedTime(LocalDateTime updatedTime) {
            this.updatedTime = updatedTime;
            return this;
        }

        /**
         * Setter for visibility.
         * @param  visibility  Visibility value for visibility.
         * @return Builder
         */
        public Builder visibility(Visibility visibility) {
            this.visibility = visibility;
            return this;
        }

        /**
         * Setter for roleAssignments.
         * @param  roleAssignments  CatalogCollectionRoleAssignments value for roleAssignments.
         * @return Builder
         */
        public Builder roleAssignments(CatalogCollectionRoleAssignments roleAssignments) {
            this.roleAssignments = roleAssignments;
            return this;
        }

        /**
         * Setter for coverAsset.
         * @param  coverAsset  CatalogCollectionItem value for coverAsset.
         * @return Builder
         */
        public Builder coverAsset(CatalogCollectionItem coverAsset) {
            this.coverAsset = coverAsset;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CatalogCollection} object using the set fields.
         * @return {@link CatalogCollection}
         */
        public CatalogCollection build() {
            CatalogCollection model =
                    new CatalogCollection(id, name, totalItemCount, createdTime, updatedTime,
                            visibility, roleAssignments, coverAsset);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
