/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for CatalogCollectionRoleAssignments type.
 */
public class CatalogCollectionRoleAssignments {
    private String collectionId;
    private Roles roles;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CatalogCollectionRoleAssignments() {
    }

    /**
     * Initialization constructor.
     * @param  collectionId  String value for collectionId.
     * @param  roles  Roles value for roles.
     */
    public CatalogCollectionRoleAssignments(
            String collectionId,
            Roles roles) {
        this.collectionId = collectionId;
        this.roles = roles;
    }

    /**
     * Getter for CollectionId.
     * @return Returns the String
     */
    @JsonGetter("collection_id")
    public String getCollectionId() {
        return collectionId;
    }

    /**
     * Setter for CollectionId.
     * @param collectionId Value for String
     */
    @JsonSetter("collection_id")
    public void setCollectionId(String collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * Getter for Roles.
     * @return Returns the Roles
     */
    @JsonGetter("roles")
    public Roles getRoles() {
        return roles;
    }

    /**
     * Setter for Roles.
     * @param roles Value for Roles
     */
    @JsonSetter("roles")
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CatalogCollectionRoleAssignments into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CatalogCollectionRoleAssignments [" + "collectionId=" + collectionId + ", roles="
                + roles + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CatalogCollectionRoleAssignments.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CatalogCollectionRoleAssignments.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(collectionId, roles);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CatalogCollectionRoleAssignments}.
     */
    public static class Builder {
        private String collectionId;
        private Roles roles;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  collectionId  String value for collectionId.
         * @param  roles  Roles value for roles.
         */
        public Builder(String collectionId, Roles roles) {
            this.collectionId = collectionId;
            this.roles = roles;
        }

        /**
         * Setter for collectionId.
         * @param  collectionId  String value for collectionId.
         * @return Builder
         */
        public Builder collectionId(String collectionId) {
            this.collectionId = collectionId;
            return this;
        }

        /**
         * Setter for roles.
         * @param  roles  Roles value for roles.
         * @return Builder
         */
        public Builder roles(Roles roles) {
            this.roles = roles;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CatalogCollectionRoleAssignments} object using the set fields.
         * @return {@link CatalogCollectionRoleAssignments}
         */
        public CatalogCollectionRoleAssignments build() {
            CatalogCollectionRoleAssignments model =
                    new CatalogCollectionRoleAssignments(collectionId, roles);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
