/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for CatalogCollectionItem type.
 */
public class CatalogCollectionItem {
    private String id;
    private Asset asset;
    private LocalDateTime createdTime;
    private List<String> collectionIds;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CatalogCollectionItem() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  asset  Asset value for asset.
     * @param  createdTime  LocalDateTime value for createdTime.
     * @param  collectionIds  List of String value for collectionIds.
     */
    public CatalogCollectionItem(
            String id,
            Asset asset,
            LocalDateTime createdTime,
            List<String> collectionIds) {
        this.id = id;
        this.asset = asset;
        this.createdTime = createdTime;
        this.collectionIds = collectionIds;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Asset.
     * @return Returns the Asset
     */
    @JsonGetter("asset")
    public Asset getAsset() {
        return asset;
    }

    /**
     * Setter for Asset.
     * @param asset Value for Asset
     */
    @JsonSetter("asset")
    public void setAsset(Asset asset) {
        this.asset = asset;
    }

    /**
     * Getter for CreatedTime.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created_time")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * Setter for CreatedTime.
     * @param createdTime Value for LocalDateTime
     */
    @JsonSetter("created_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * Getter for CollectionIds.
     * The collection IDs that this asset belongs to
     * @return Returns the List of String
     */
    @JsonGetter("collection_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getCollectionIds() {
        return collectionIds;
    }

    /**
     * Setter for CollectionIds.
     * The collection IDs that this asset belongs to
     * @param collectionIds Value for List of String
     */
    @JsonSetter("collection_ids")
    public void setCollectionIds(List<String> collectionIds) {
        this.collectionIds = collectionIds;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CatalogCollectionItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CatalogCollectionItem [" + "id=" + id + ", asset=" + asset + ", createdTime="
                + createdTime + ", collectionIds=" + collectionIds + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CatalogCollectionItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CatalogCollectionItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, asset, createdTime)
                .collectionIds(getCollectionIds());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CatalogCollectionItem}.
     */
    public static class Builder {
        private String id;
        private Asset asset;
        private LocalDateTime createdTime;
        private List<String> collectionIds;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  asset  Asset value for asset.
         * @param  createdTime  LocalDateTime value for createdTime.
         */
        public Builder(String id, Asset asset, LocalDateTime createdTime) {
            this.id = id;
            this.asset = asset;
            this.createdTime = createdTime;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for asset.
         * @param  asset  Asset value for asset.
         * @return Builder
         */
        public Builder asset(Asset asset) {
            this.asset = asset;
            return this;
        }

        /**
         * Setter for createdTime.
         * @param  createdTime  LocalDateTime value for createdTime.
         * @return Builder
         */
        public Builder createdTime(LocalDateTime createdTime) {
            this.createdTime = createdTime;
            return this;
        }

        /**
         * Setter for collectionIds.
         * @param  collectionIds  List of String value for collectionIds.
         * @return Builder
         */
        public Builder collectionIds(List<String> collectionIds) {
            this.collectionIds = collectionIds;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CatalogCollectionItem} object using the set fields.
         * @return {@link CatalogCollectionItem}
         */
        public CatalogCollectionItem build() {
            CatalogCollectionItem model =
                    new CatalogCollectionItem(id, asset, createdTime, collectionIds);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
