/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ComputerVisionImageCreateResponse type.
 */
public class ComputerVisionImageCreateResponse {
    private String uploadId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ComputerVisionImageCreateResponse() {
    }

    /**
     * Initialization constructor.
     * @param  uploadId  String value for uploadId.
     */
    public ComputerVisionImageCreateResponse(
            String uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * Getter for UploadId.
     * @return Returns the String
     */
    @JsonGetter("upload_id")
    public String getUploadId() {
        return uploadId;
    }

    /**
     * Setter for UploadId.
     * @param uploadId Value for String
     */
    @JsonSetter("upload_id")
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ComputerVisionImageCreateResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ComputerVisionImageCreateResponse [" + "uploadId=" + uploadId
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ComputerVisionImageCreateResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ComputerVisionImageCreateResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(uploadId);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ComputerVisionImageCreateResponse}.
     */
    public static class Builder {
        private String uploadId;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  uploadId  String value for uploadId.
         */
        public Builder(String uploadId) {
            this.uploadId = uploadId;
        }

        /**
         * Setter for uploadId.
         * @param  uploadId  String value for uploadId.
         * @return Builder
         */
        public Builder uploadId(String uploadId) {
            this.uploadId = uploadId;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ComputerVisionImageCreateResponse} object using the set fields.
         * @return {@link ComputerVisionImageCreateResponse}
         */
        public ComputerVisionImageCreateResponse build() {
            ComputerVisionImageCreateResponse model =
                    new ComputerVisionImageCreateResponse(uploadId);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
