/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ContributorProfile type.
 */
public class ContributorProfile {
    private String about;
    private List<String> contributorType;
    private String displayName;
    private List<String> equipment;
    private String id;
    private String location;
    private String portfolioUrl;
    private ContributorProfileSocialMedia socialMedia;
    private List<String> styles;
    private List<String> subjects;
    private String website;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ContributorProfile() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  about  String value for about.
     * @param  contributorType  List of String value for contributorType.
     * @param  displayName  String value for displayName.
     * @param  equipment  List of String value for equipment.
     * @param  location  String value for location.
     * @param  portfolioUrl  String value for portfolioUrl.
     * @param  socialMedia  ContributorProfileSocialMedia value for socialMedia.
     * @param  styles  List of String value for styles.
     * @param  subjects  List of String value for subjects.
     * @param  website  String value for website.
     */
    public ContributorProfile(
            String id,
            String about,
            List<String> contributorType,
            String displayName,
            List<String> equipment,
            String location,
            String portfolioUrl,
            ContributorProfileSocialMedia socialMedia,
            List<String> styles,
            List<String> subjects,
            String website) {
        this.about = about;
        this.contributorType = contributorType;
        this.displayName = displayName;
        this.equipment = equipment;
        this.id = id;
        this.location = location;
        this.portfolioUrl = portfolioUrl;
        this.socialMedia = socialMedia;
        this.styles = styles;
        this.subjects = subjects;
        this.website = website;
    }

    /**
     * Getter for About.
     * Short description of the contributors' library
     * @return Returns the String
     */
    @JsonGetter("about")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAbout() {
        return about;
    }

    /**
     * Setter for About.
     * Short description of the contributors' library
     * @param about Value for String
     */
    @JsonSetter("about")
    public void setAbout(String about) {
        this.about = about;
    }

    /**
     * Getter for ContributorType.
     * Type of content that the contributor specializes in (photographer, illustrator, etc)
     * @return Returns the List of String
     */
    @JsonGetter("contributor_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getContributorType() {
        return contributorType;
    }

    /**
     * Setter for ContributorType.
     * Type of content that the contributor specializes in (photographer, illustrator, etc)
     * @param contributorType Value for List of String
     */
    @JsonSetter("contributor_type")
    public void setContributorType(List<String> contributorType) {
        this.contributorType = contributorType;
    }

    /**
     * Getter for DisplayName.
     * Preferred name to be displayed for the contributor
     * @return Returns the String
     */
    @JsonGetter("display_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * Preferred name to be displayed for the contributor
     * @param displayName Value for String
     */
    @JsonSetter("display_name")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Getter for Equipment.
     * List of equipment used by the contributor (Canon EOS 5D Mark II, etc)
     * @return Returns the List of String
     */
    @JsonGetter("equipment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getEquipment() {
        return equipment;
    }

    /**
     * Setter for Equipment.
     * List of equipment used by the contributor (Canon EOS 5D Mark II, etc)
     * @param equipment Value for List of String
     */
    @JsonSetter("equipment")
    public void setEquipment(List<String> equipment) {
        this.equipment = equipment;
    }

    /**
     * Getter for Id.
     * Contributor ID
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Contributor ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Location.
     * Country code representing the contributor's locale
     * @return Returns the String
     */
    @JsonGetter("location")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLocation() {
        return location;
    }

    /**
     * Setter for Location.
     * Country code representing the contributor's locale
     * @param location Value for String
     */
    @JsonSetter("location")
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Getter for PortfolioUrl.
     * Web URL for the contributors' profile
     * @return Returns the String
     */
    @JsonGetter("portfolio_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPortfolioUrl() {
        return portfolioUrl;
    }

    /**
     * Setter for PortfolioUrl.
     * Web URL for the contributors' profile
     * @param portfolioUrl Value for String
     */
    @JsonSetter("portfolio_url")
    public void setPortfolioUrl(String portfolioUrl) {
        this.portfolioUrl = portfolioUrl;
    }

    /**
     * Getter for SocialMedia.
     * Contributor profile social media links
     * @return Returns the ContributorProfileSocialMedia
     */
    @JsonGetter("social_media")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ContributorProfileSocialMedia getSocialMedia() {
        return socialMedia;
    }

    /**
     * Setter for SocialMedia.
     * Contributor profile social media links
     * @param socialMedia Value for ContributorProfileSocialMedia
     */
    @JsonSetter("social_media")
    public void setSocialMedia(ContributorProfileSocialMedia socialMedia) {
        this.socialMedia = socialMedia;
    }

    /**
     * Getter for Styles.
     * List of styles that the contributor specializes in (lifestyle, mixed media, etc)
     * @return Returns the List of String
     */
    @JsonGetter("styles")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getStyles() {
        return styles;
    }

    /**
     * Setter for Styles.
     * List of styles that the contributor specializes in (lifestyle, mixed media, etc)
     * @param styles Value for List of String
     */
    @JsonSetter("styles")
    public void setStyles(List<String> styles) {
        this.styles = styles;
    }

    /**
     * Getter for Subjects.
     * Generic list of subjects for contributors' work (food_and_drink, holiday, people, etc)
     * @return Returns the List of String
     */
    @JsonGetter("subjects")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getSubjects() {
        return subjects;
    }

    /**
     * Setter for Subjects.
     * Generic list of subjects for contributors' work (food_and_drink, holiday, people, etc)
     * @param subjects Value for List of String
     */
    @JsonSetter("subjects")
    public void setSubjects(List<String> subjects) {
        this.subjects = subjects;
    }

    /**
     * Getter for Website.
     * Personal website for the contributor
     * @return Returns the String
     */
    @JsonGetter("website")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWebsite() {
        return website;
    }

    /**
     * Setter for Website.
     * Personal website for the contributor
     * @param website Value for String
     */
    @JsonSetter("website")
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ContributorProfile into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ContributorProfile [" + "id=" + id + ", about=" + about + ", contributorType="
                + contributorType + ", displayName=" + displayName + ", equipment=" + equipment
                + ", location=" + location + ", portfolioUrl=" + portfolioUrl + ", socialMedia="
                + socialMedia + ", styles=" + styles + ", subjects=" + subjects + ", website="
                + website + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ContributorProfile.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ContributorProfile.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id)
                .about(getAbout())
                .contributorType(getContributorType())
                .displayName(getDisplayName())
                .equipment(getEquipment())
                .location(getLocation())
                .portfolioUrl(getPortfolioUrl())
                .socialMedia(getSocialMedia())
                .styles(getStyles())
                .subjects(getSubjects())
                .website(getWebsite());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ContributorProfile}.
     */
    public static class Builder {
        private String id;
        private String about;
        private List<String> contributorType;
        private String displayName;
        private List<String> equipment;
        private String location;
        private String portfolioUrl;
        private ContributorProfileSocialMedia socialMedia;
        private List<String> styles;
        private List<String> subjects;
        private String website;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         */
        public Builder(String id) {
            this.id = id;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for about.
         * @param  about  String value for about.
         * @return Builder
         */
        public Builder about(String about) {
            this.about = about;
            return this;
        }

        /**
         * Setter for contributorType.
         * @param  contributorType  List of String value for contributorType.
         * @return Builder
         */
        public Builder contributorType(List<String> contributorType) {
            this.contributorType = contributorType;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Setter for equipment.
         * @param  equipment  List of String value for equipment.
         * @return Builder
         */
        public Builder equipment(List<String> equipment) {
            this.equipment = equipment;
            return this;
        }

        /**
         * Setter for location.
         * @param  location  String value for location.
         * @return Builder
         */
        public Builder location(String location) {
            this.location = location;
            return this;
        }

        /**
         * Setter for portfolioUrl.
         * @param  portfolioUrl  String value for portfolioUrl.
         * @return Builder
         */
        public Builder portfolioUrl(String portfolioUrl) {
            this.portfolioUrl = portfolioUrl;
            return this;
        }

        /**
         * Setter for socialMedia.
         * @param  socialMedia  ContributorProfileSocialMedia value for socialMedia.
         * @return Builder
         */
        public Builder socialMedia(ContributorProfileSocialMedia socialMedia) {
            this.socialMedia = socialMedia;
            return this;
        }

        /**
         * Setter for styles.
         * @param  styles  List of String value for styles.
         * @return Builder
         */
        public Builder styles(List<String> styles) {
            this.styles = styles;
            return this;
        }

        /**
         * Setter for subjects.
         * @param  subjects  List of String value for subjects.
         * @return Builder
         */
        public Builder subjects(List<String> subjects) {
            this.subjects = subjects;
            return this;
        }

        /**
         * Setter for website.
         * @param  website  String value for website.
         * @return Builder
         */
        public Builder website(String website) {
            this.website = website;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ContributorProfile} object using the set fields.
         * @return {@link ContributorProfile}
         */
        public ContributorProfile build() {
            ContributorProfile model =
                    new ContributorProfile(id, about, contributorType, displayName, equipment,
                            location, portfolioUrl, socialMedia, styles, subjects, website);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
