/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ContributorProfileDataList type.
 */
public class ContributorProfileDataList {
    private List<ContributorProfile> data;
    private List<Error> errors;
    private String message;
    private Integer page;
    private Integer perPage;
    private Integer totalCount;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ContributorProfileDataList() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of ContributorProfile value for data.
     * @param  errors  List of Error value for errors.
     * @param  message  String value for message.
     * @param  page  Integer value for page.
     * @param  perPage  Integer value for perPage.
     * @param  totalCount  Integer value for totalCount.
     */
    public ContributorProfileDataList(
            List<ContributorProfile> data,
            List<Error> errors,
            String message,
            Integer page,
            Integer perPage,
            Integer totalCount) {
        this.data = data;
        this.errors = errors;
        this.message = message;
        this.page = page;
        this.perPage = perPage;
        this.totalCount = totalCount;
    }

    /**
     * Getter for Data.
     * Conributor profiles
     * @return Returns the List of ContributorProfile
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ContributorProfile> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Conributor profiles
     * @param data Value for List of ContributorProfile
     */
    @JsonSetter("data")
    public void setData(List<ContributorProfile> data) {
        this.data = data;
    }

    /**
     * Getter for Errors.
     * Error list; appears only if there was an error
     * @return Returns the List of Error
     */
    @JsonGetter("errors")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Error> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * Error list; appears only if there was an error
     * @param errors Value for List of Error
     */
    @JsonSetter("errors")
    public void setErrors(List<Error> errors) {
        this.errors = errors;
    }

    /**
     * Getter for Message.
     * Error message
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * Error message
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Page.
     * Page of response
     * @return Returns the Integer
     */
    @JsonGetter("page")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPage() {
        return page;
    }

    /**
     * Setter for Page.
     * Page of response
     * @param page Value for Integer
     */
    @JsonSetter("page")
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * Getter for PerPage.
     * Number of contributors per page
     * @return Returns the Integer
     */
    @JsonGetter("per_page")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPerPage() {
        return perPage;
    }

    /**
     * Setter for PerPage.
     * Number of contributors per page
     * @param perPage Value for Integer
     */
    @JsonSetter("per_page")
    public void setPerPage(Integer perPage) {
        this.perPage = perPage;
    }

    /**
     * Getter for TotalCount.
     * Total count of contributors for this request
     * @return Returns the Integer
     */
    @JsonGetter("total_count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * Setter for TotalCount.
     * Total count of contributors for this request
     * @param totalCount Value for Integer
     */
    @JsonSetter("total_count")
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ContributorProfileDataList into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ContributorProfileDataList [" + "data=" + data + ", errors=" + errors + ", message="
                + message + ", page=" + page + ", perPage=" + perPage + ", totalCount=" + totalCount
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ContributorProfileDataList.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ContributorProfileDataList.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .data(getData())
                .errors(getErrors())
                .message(getMessage())
                .page(getPage())
                .perPage(getPerPage())
                .totalCount(getTotalCount());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ContributorProfileDataList}.
     */
    public static class Builder {
        private List<ContributorProfile> data;
        private List<Error> errors;
        private String message;
        private Integer page;
        private Integer perPage;
        private Integer totalCount;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for data.
         * @param  data  List of ContributorProfile value for data.
         * @return Builder
         */
        public Builder data(List<ContributorProfile> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  List of Error value for errors.
         * @return Builder
         */
        public Builder errors(List<Error> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for page.
         * @param  page  Integer value for page.
         * @return Builder
         */
        public Builder page(Integer page) {
            this.page = page;
            return this;
        }

        /**
         * Setter for perPage.
         * @param  perPage  Integer value for perPage.
         * @return Builder
         */
        public Builder perPage(Integer perPage) {
            this.perPage = perPage;
            return this;
        }

        /**
         * Setter for totalCount.
         * @param  totalCount  Integer value for totalCount.
         * @return Builder
         */
        public Builder totalCount(Integer totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ContributorProfileDataList} object using the set fields.
         * @return {@link ContributorProfileDataList}
         */
        public ContributorProfileDataList build() {
            ContributorProfileDataList model =
                    new ContributorProfileDataList(data, errors, message, page, perPage,
                            totalCount);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
