/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for EditorialVideoContent type.
 */
public class EditorialVideoContent {
    private Double aspect;
    private EditorialVideoAssets assets;
    private String byline;
    private String caption;
    private List<EditorialCategory> categories;
    private LocalDate dateTaken;
    private String description;
    private String id;
    private List<String> keywords;
    private String title;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public EditorialVideoContent() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  aspect  Double value for aspect.
     * @param  assets  EditorialVideoAssets value for assets.
     * @param  byline  String value for byline.
     * @param  caption  String value for caption.
     * @param  categories  List of EditorialCategory value for categories.
     * @param  dateTaken  LocalDate value for dateTaken.
     * @param  description  String value for description.
     * @param  keywords  List of String value for keywords.
     * @param  title  String value for title.
     */
    public EditorialVideoContent(
            String id,
            Double aspect,
            EditorialVideoAssets assets,
            String byline,
            String caption,
            List<EditorialCategory> categories,
            LocalDate dateTaken,
            String description,
            List<String> keywords,
            String title) {
        this.aspect = aspect;
        this.assets = assets;
        this.byline = byline;
        this.caption = caption;
        this.categories = categories;
        this.dateTaken = dateTaken;
        this.description = description;
        this.id = id;
        this.keywords = keywords;
        this.title = title;
    }

    /**
     * Getter for Aspect.
     * @return Returns the Double
     */
    @JsonGetter("aspect")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAspect() {
        return aspect;
    }

    /**
     * Setter for Aspect.
     * @param aspect Value for Double
     */
    @JsonSetter("aspect")
    public void setAspect(Double aspect) {
        this.aspect = aspect;
    }

    /**
     * Getter for Assets.
     * Asset information, including size and thumbnail URLs
     * @return Returns the EditorialVideoAssets
     */
    @JsonGetter("assets")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EditorialVideoAssets getAssets() {
        return assets;
    }

    /**
     * Setter for Assets.
     * Asset information, including size and thumbnail URLs
     * @param assets Value for EditorialVideoAssets
     */
    @JsonSetter("assets")
    public void setAssets(EditorialVideoAssets assets) {
        this.assets = assets;
    }

    /**
     * Getter for Byline.
     * @return Returns the String
     */
    @JsonGetter("byline")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getByline() {
        return byline;
    }

    /**
     * Setter for Byline.
     * @param byline Value for String
     */
    @JsonSetter("byline")
    public void setByline(String byline) {
        this.byline = byline;
    }

    /**
     * Getter for Caption.
     * @return Returns the String
     */
    @JsonGetter("caption")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCaption() {
        return caption;
    }

    /**
     * Setter for Caption.
     * @param caption Value for String
     */
    @JsonSetter("caption")
    public void setCaption(String caption) {
        this.caption = caption;
    }

    /**
     * Getter for Categories.
     * List of categories
     * @return Returns the List of EditorialCategory
     */
    @JsonGetter("categories")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<EditorialCategory> getCategories() {
        return categories;
    }

    /**
     * Setter for Categories.
     * List of categories
     * @param categories Value for List of EditorialCategory
     */
    @JsonSetter("categories")
    public void setCategories(List<EditorialCategory> categories) {
        this.categories = categories;
    }

    /**
     * Getter for DateTaken.
     * @return Returns the LocalDate
     */
    @JsonGetter("date_taken")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getDateTaken() {
        return dateTaken;
    }

    /**
     * Setter for DateTaken.
     * @param dateTaken Value for LocalDate
     */
    @JsonSetter("date_taken")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setDateTaken(LocalDate dateTaken) {
        this.dateTaken = dateTaken;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Keywords.
     * @return Returns the List of String
     */
    @JsonGetter("keywords")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getKeywords() {
        return keywords;
    }

    /**
     * Setter for Keywords.
     * @param keywords Value for List of String
     */
    @JsonSetter("keywords")
    public void setKeywords(List<String> keywords) {
        this.keywords = keywords;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this EditorialVideoContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EditorialVideoContent [" + "id=" + id + ", aspect=" + aspect + ", assets=" + assets
                + ", byline=" + byline + ", caption=" + caption + ", categories=" + categories
                + ", dateTaken=" + dateTaken + ", description=" + description + ", keywords="
                + keywords + ", title=" + title + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link EditorialVideoContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EditorialVideoContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id)
                .aspect(getAspect())
                .assets(getAssets())
                .byline(getByline())
                .caption(getCaption())
                .categories(getCategories())
                .dateTaken(getDateTaken())
                .description(getDescription())
                .keywords(getKeywords())
                .title(getTitle());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link EditorialVideoContent}.
     */
    public static class Builder {
        private String id;
        private Double aspect;
        private EditorialVideoAssets assets;
        private String byline;
        private String caption;
        private List<EditorialCategory> categories;
        private LocalDate dateTaken;
        private String description;
        private List<String> keywords;
        private String title;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         */
        public Builder(String id) {
            this.id = id;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for aspect.
         * @param  aspect  Double value for aspect.
         * @return Builder
         */
        public Builder aspect(Double aspect) {
            this.aspect = aspect;
            return this;
        }

        /**
         * Setter for assets.
         * @param  assets  EditorialVideoAssets value for assets.
         * @return Builder
         */
        public Builder assets(EditorialVideoAssets assets) {
            this.assets = assets;
            return this;
        }

        /**
         * Setter for byline.
         * @param  byline  String value for byline.
         * @return Builder
         */
        public Builder byline(String byline) {
            this.byline = byline;
            return this;
        }

        /**
         * Setter for caption.
         * @param  caption  String value for caption.
         * @return Builder
         */
        public Builder caption(String caption) {
            this.caption = caption;
            return this;
        }

        /**
         * Setter for categories.
         * @param  categories  List of EditorialCategory value for categories.
         * @return Builder
         */
        public Builder categories(List<EditorialCategory> categories) {
            this.categories = categories;
            return this;
        }

        /**
         * Setter for dateTaken.
         * @param  dateTaken  LocalDate value for dateTaken.
         * @return Builder
         */
        public Builder dateTaken(LocalDate dateTaken) {
            this.dateTaken = dateTaken;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for keywords.
         * @param  keywords  List of String value for keywords.
         * @return Builder
         */
        public Builder keywords(List<String> keywords) {
            this.keywords = keywords;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link EditorialVideoContent} object using the set fields.
         * @return {@link EditorialVideoContent}
         */
        public EditorialVideoContent build() {
            EditorialVideoContent model =
                    new EditorialVideoContent(id, aspect, assets, byline, caption, categories,
                            dateTaken, description, keywords, title);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
