/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for EditorialAssets type.
 */
public class EditorialAssets {
    private ImageSizeDetails original;
    private Thumbnail thumb170;
    private Thumbnail thumb220;
    private Thumbnail watermark450;
    private Thumbnail watermark1500;
    private ImageSizeDetails smallJpg;
    private ImageSizeDetails mediumJpg;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public EditorialAssets() {
    }

    /**
     * Initialization constructor.
     * @param  original  ImageSizeDetails value for original.
     * @param  thumb170  Thumbnail value for thumb170.
     * @param  thumb220  Thumbnail value for thumb220.
     * @param  watermark450  Thumbnail value for watermark450.
     * @param  watermark1500  Thumbnail value for watermark1500.
     * @param  smallJpg  ImageSizeDetails value for smallJpg.
     * @param  mediumJpg  ImageSizeDetails value for mediumJpg.
     */
    public EditorialAssets(
            ImageSizeDetails original,
            Thumbnail thumb170,
            Thumbnail thumb220,
            Thumbnail watermark450,
            Thumbnail watermark1500,
            ImageSizeDetails smallJpg,
            ImageSizeDetails mediumJpg) {
        this.original = original;
        this.thumb170 = thumb170;
        this.thumb220 = thumb220;
        this.watermark450 = watermark450;
        this.watermark1500 = watermark1500;
        this.smallJpg = smallJpg;
        this.mediumJpg = mediumJpg;
    }

    /**
     * Getter for Original.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("original")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getOriginal() {
        return original;
    }

    /**
     * Setter for Original.
     * Image size information
     * @param original Value for ImageSizeDetails
     */
    @JsonSetter("original")
    public void setOriginal(ImageSizeDetails original) {
        this.original = original;
    }

    /**
     * Getter for Thumb170.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("thumb_170")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getThumb170() {
        return thumb170;
    }

    /**
     * Setter for Thumb170.
     * Image thumbnail information
     * @param thumb170 Value for Thumbnail
     */
    @JsonSetter("thumb_170")
    public void setThumb170(Thumbnail thumb170) {
        this.thumb170 = thumb170;
    }

    /**
     * Getter for Thumb220.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("thumb_220")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getThumb220() {
        return thumb220;
    }

    /**
     * Setter for Thumb220.
     * Image thumbnail information
     * @param thumb220 Value for Thumbnail
     */
    @JsonSetter("thumb_220")
    public void setThumb220(Thumbnail thumb220) {
        this.thumb220 = thumb220;
    }

    /**
     * Getter for Watermark450.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("watermark_450")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getWatermark450() {
        return watermark450;
    }

    /**
     * Setter for Watermark450.
     * Image thumbnail information
     * @param watermark450 Value for Thumbnail
     */
    @JsonSetter("watermark_450")
    public void setWatermark450(Thumbnail watermark450) {
        this.watermark450 = watermark450;
    }

    /**
     * Getter for Watermark1500.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("watermark_1500")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getWatermark1500() {
        return watermark1500;
    }

    /**
     * Setter for Watermark1500.
     * Image thumbnail information
     * @param watermark1500 Value for Thumbnail
     */
    @JsonSetter("watermark_1500")
    public void setWatermark1500(Thumbnail watermark1500) {
        this.watermark1500 = watermark1500;
    }

    /**
     * Getter for SmallJpg.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("small_jpg")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getSmallJpg() {
        return smallJpg;
    }

    /**
     * Setter for SmallJpg.
     * Image size information
     * @param smallJpg Value for ImageSizeDetails
     */
    @JsonSetter("small_jpg")
    public void setSmallJpg(ImageSizeDetails smallJpg) {
        this.smallJpg = smallJpg;
    }

    /**
     * Getter for MediumJpg.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("medium_jpg")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getMediumJpg() {
        return mediumJpg;
    }

    /**
     * Setter for MediumJpg.
     * Image size information
     * @param mediumJpg Value for ImageSizeDetails
     */
    @JsonSetter("medium_jpg")
    public void setMediumJpg(ImageSizeDetails mediumJpg) {
        this.mediumJpg = mediumJpg;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this EditorialAssets into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EditorialAssets [" + "original=" + original + ", thumb170=" + thumb170
                + ", thumb220=" + thumb220 + ", watermark450=" + watermark450 + ", watermark1500="
                + watermark1500 + ", smallJpg=" + smallJpg + ", mediumJpg=" + mediumJpg
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link EditorialAssets.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EditorialAssets.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .original(getOriginal())
                .thumb170(getThumb170())
                .thumb220(getThumb220())
                .watermark450(getWatermark450())
                .watermark1500(getWatermark1500())
                .smallJpg(getSmallJpg())
                .mediumJpg(getMediumJpg());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link EditorialAssets}.
     */
    public static class Builder {
        private ImageSizeDetails original;
        private Thumbnail thumb170;
        private Thumbnail thumb220;
        private Thumbnail watermark450;
        private Thumbnail watermark1500;
        private ImageSizeDetails smallJpg;
        private ImageSizeDetails mediumJpg;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for original.
         * @param  original  ImageSizeDetails value for original.
         * @return Builder
         */
        public Builder original(ImageSizeDetails original) {
            this.original = original;
            return this;
        }

        /**
         * Setter for thumb170.
         * @param  thumb170  Thumbnail value for thumb170.
         * @return Builder
         */
        public Builder thumb170(Thumbnail thumb170) {
            this.thumb170 = thumb170;
            return this;
        }

        /**
         * Setter for thumb220.
         * @param  thumb220  Thumbnail value for thumb220.
         * @return Builder
         */
        public Builder thumb220(Thumbnail thumb220) {
            this.thumb220 = thumb220;
            return this;
        }

        /**
         * Setter for watermark450.
         * @param  watermark450  Thumbnail value for watermark450.
         * @return Builder
         */
        public Builder watermark450(Thumbnail watermark450) {
            this.watermark450 = watermark450;
            return this;
        }

        /**
         * Setter for watermark1500.
         * @param  watermark1500  Thumbnail value for watermark1500.
         * @return Builder
         */
        public Builder watermark1500(Thumbnail watermark1500) {
            this.watermark1500 = watermark1500;
            return this;
        }

        /**
         * Setter for smallJpg.
         * @param  smallJpg  ImageSizeDetails value for smallJpg.
         * @return Builder
         */
        public Builder smallJpg(ImageSizeDetails smallJpg) {
            this.smallJpg = smallJpg;
            return this;
        }

        /**
         * Setter for mediumJpg.
         * @param  mediumJpg  ImageSizeDetails value for mediumJpg.
         * @return Builder
         */
        public Builder mediumJpg(ImageSizeDetails mediumJpg) {
            this.mediumJpg = mediumJpg;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link EditorialAssets} object using the set fields.
         * @return {@link EditorialAssets}
         */
        public EditorialAssets build() {
            EditorialAssets model =
                    new EditorialAssets(original, thumb170, thumb220, watermark450, watermark1500,
                            smallJpg, mediumJpg);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
