/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * GrantType to be used.
 */
public enum GrantType {
    AUTHORIZATION_CODE,

    CLIENT_CREDENTIALS,

    REFRESH_TOKEN;

    private static TreeMap<String, GrantType> valueMap = new TreeMap<>();
    private String value;

    static {
        AUTHORIZATION_CODE.value = "authorization_code";
        CLIENT_CREDENTIALS.value = "client_credentials";
        REFRESH_TOKEN.value = "refresh_token";

        valueMap.put("authorization_code", AUTHORIZATION_CODE);
        valueMap.put("client_credentials", CLIENT_CREDENTIALS);
        valueMap.put("refresh_token", REFRESH_TOKEN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static GrantType constructFromString(String toConvert) throws IOException {
        GrantType enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static GrantType fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of GrantType values to list of string values.
     * @param toConvert The list of GrantType values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<GrantType> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (GrantType enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 