/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ImageSizeDetails type.
 */
public class ImageSizeDetails {
    private String displayName;
    private Integer dpi;
    private Integer fileSize;
    private String format;
    private Integer height;
    private Boolean isLicensable;
    private Integer width;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ImageSizeDetails() {
    }

    /**
     * Initialization constructor.
     * @param  displayName  String value for displayName.
     * @param  dpi  Integer value for dpi.
     * @param  fileSize  Integer value for fileSize.
     * @param  format  String value for format.
     * @param  height  Integer value for height.
     * @param  isLicensable  Boolean value for isLicensable.
     * @param  width  Integer value for width.
     */
    public ImageSizeDetails(
            String displayName,
            Integer dpi,
            Integer fileSize,
            String format,
            Integer height,
            Boolean isLicensable,
            Integer width) {
        this.displayName = displayName;
        this.dpi = dpi;
        this.fileSize = fileSize;
        this.format = format;
        this.height = height;
        this.isLicensable = isLicensable;
        this.width = width;
    }

    /**
     * Getter for DisplayName.
     * Display name of this image size
     * @return Returns the String
     */
    @JsonGetter("display_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * Display name of this image size
     * @param displayName Value for String
     */
    @JsonSetter("display_name")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Getter for Dpi.
     * @return Returns the Integer
     */
    @JsonGetter("dpi")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDpi() {
        return dpi;
    }

    /**
     * Setter for Dpi.
     * @param dpi Value for Integer
     */
    @JsonSetter("dpi")
    public void setDpi(Integer dpi) {
        this.dpi = dpi;
    }

    /**
     * Getter for FileSize.
     * File size (in bytes) of this image size
     * @return Returns the Integer
     */
    @JsonGetter("file_size")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * Setter for FileSize.
     * File size (in bytes) of this image size
     * @param fileSize Value for Integer
     */
    @JsonSetter("file_size")
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * Getter for Format.
     * Format of this image size
     * @return Returns the String
     */
    @JsonGetter("format")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFormat() {
        return format;
    }

    /**
     * Setter for Format.
     * Format of this image size
     * @param format Value for String
     */
    @JsonSetter("format")
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * Getter for Height.
     * Height of this image size
     * @return Returns the Integer
     */
    @JsonGetter("height")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getHeight() {
        return height;
    }

    /**
     * Setter for Height.
     * Height of this image size
     * @param height Value for Integer
     */
    @JsonSetter("height")
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * Getter for IsLicensable.
     * Whether or not this image can be licensed in this image size
     * @return Returns the Boolean
     */
    @JsonGetter("is_licensable")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsLicensable() {
        return isLicensable;
    }

    /**
     * Setter for IsLicensable.
     * Whether or not this image can be licensed in this image size
     * @param isLicensable Value for Boolean
     */
    @JsonSetter("is_licensable")
    public void setIsLicensable(Boolean isLicensable) {
        this.isLicensable = isLicensable;
    }

    /**
     * Getter for Width.
     * Width of this image size
     * @return Returns the Integer
     */
    @JsonGetter("width")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getWidth() {
        return width;
    }

    /**
     * Setter for Width.
     * Width of this image size
     * @param width Value for Integer
     */
    @JsonSetter("width")
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ImageSizeDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ImageSizeDetails [" + "displayName=" + displayName + ", dpi=" + dpi + ", fileSize="
                + fileSize + ", format=" + format + ", height=" + height + ", isLicensable="
                + isLicensable + ", width=" + width + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ImageSizeDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ImageSizeDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .displayName(getDisplayName())
                .dpi(getDpi())
                .fileSize(getFileSize())
                .format(getFormat())
                .height(getHeight())
                .isLicensable(getIsLicensable())
                .width(getWidth());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ImageSizeDetails}.
     */
    public static class Builder {
        private String displayName;
        private Integer dpi;
        private Integer fileSize;
        private String format;
        private Integer height;
        private Boolean isLicensable;
        private Integer width;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Setter for dpi.
         * @param  dpi  Integer value for dpi.
         * @return Builder
         */
        public Builder dpi(Integer dpi) {
            this.dpi = dpi;
            return this;
        }

        /**
         * Setter for fileSize.
         * @param  fileSize  Integer value for fileSize.
         * @return Builder
         */
        public Builder fileSize(Integer fileSize) {
            this.fileSize = fileSize;
            return this;
        }

        /**
         * Setter for format.
         * @param  format  String value for format.
         * @return Builder
         */
        public Builder format(String format) {
            this.format = format;
            return this;
        }

        /**
         * Setter for height.
         * @param  height  Integer value for height.
         * @return Builder
         */
        public Builder height(Integer height) {
            this.height = height;
            return this;
        }

        /**
         * Setter for isLicensable.
         * @param  isLicensable  Boolean value for isLicensable.
         * @return Builder
         */
        public Builder isLicensable(Boolean isLicensable) {
            this.isLicensable = isLicensable;
            return this;
        }

        /**
         * Setter for width.
         * @param  width  Integer value for width.
         * @return Builder
         */
        public Builder width(Integer width) {
            this.width = width;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ImageSizeDetails} object using the set fields.
         * @return {@link ImageSizeDetails}
         */
        public ImageSizeDetails build() {
            ImageSizeDetails model =
                    new ImageSizeDetails(displayName, dpi, fileSize, format, height, isLicensable,
                            width);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
