/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ImageAssets type.
 */
public class ImageAssets {
    private ImageSizeDetails hugeJpg;
    private Thumbnail hugeThumb;
    private Thumbnail largeThumb;
    private ImageSizeDetails mediumJpg;
    private Thumbnail preview;
    private Thumbnail preview1000;
    private Thumbnail preview1500;
    private ImageSizeDetails smallJpg;
    private Thumbnail smallThumb;
    private ImageSizeDetails supersizeJpg;
    private ImageSizeDetails vectorEps;
    private Thumbnail mosaic;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ImageAssets() {
    }

    /**
     * Initialization constructor.
     * @param  hugeJpg  ImageSizeDetails value for hugeJpg.
     * @param  hugeThumb  Thumbnail value for hugeThumb.
     * @param  largeThumb  Thumbnail value for largeThumb.
     * @param  mediumJpg  ImageSizeDetails value for mediumJpg.
     * @param  preview  Thumbnail value for preview.
     * @param  preview1000  Thumbnail value for preview1000.
     * @param  preview1500  Thumbnail value for preview1500.
     * @param  smallJpg  ImageSizeDetails value for smallJpg.
     * @param  smallThumb  Thumbnail value for smallThumb.
     * @param  supersizeJpg  ImageSizeDetails value for supersizeJpg.
     * @param  vectorEps  ImageSizeDetails value for vectorEps.
     * @param  mosaic  Thumbnail value for mosaic.
     */
    public ImageAssets(
            ImageSizeDetails hugeJpg,
            Thumbnail hugeThumb,
            Thumbnail largeThumb,
            ImageSizeDetails mediumJpg,
            Thumbnail preview,
            Thumbnail preview1000,
            Thumbnail preview1500,
            ImageSizeDetails smallJpg,
            Thumbnail smallThumb,
            ImageSizeDetails supersizeJpg,
            ImageSizeDetails vectorEps,
            Thumbnail mosaic) {
        this.hugeJpg = hugeJpg;
        this.hugeThumb = hugeThumb;
        this.largeThumb = largeThumb;
        this.mediumJpg = mediumJpg;
        this.preview = preview;
        this.preview1000 = preview1000;
        this.preview1500 = preview1500;
        this.smallJpg = smallJpg;
        this.smallThumb = smallThumb;
        this.supersizeJpg = supersizeJpg;
        this.vectorEps = vectorEps;
        this.mosaic = mosaic;
    }

    /**
     * Getter for HugeJpg.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("huge_jpg")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getHugeJpg() {
        return hugeJpg;
    }

    /**
     * Setter for HugeJpg.
     * Image size information
     * @param hugeJpg Value for ImageSizeDetails
     */
    @JsonSetter("huge_jpg")
    public void setHugeJpg(ImageSizeDetails hugeJpg) {
        this.hugeJpg = hugeJpg;
    }

    /**
     * Getter for HugeThumb.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("huge_thumb")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getHugeThumb() {
        return hugeThumb;
    }

    /**
     * Setter for HugeThumb.
     * Image thumbnail information
     * @param hugeThumb Value for Thumbnail
     */
    @JsonSetter("huge_thumb")
    public void setHugeThumb(Thumbnail hugeThumb) {
        this.hugeThumb = hugeThumb;
    }

    /**
     * Getter for LargeThumb.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("large_thumb")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getLargeThumb() {
        return largeThumb;
    }

    /**
     * Setter for LargeThumb.
     * Image thumbnail information
     * @param largeThumb Value for Thumbnail
     */
    @JsonSetter("large_thumb")
    public void setLargeThumb(Thumbnail largeThumb) {
        this.largeThumb = largeThumb;
    }

    /**
     * Getter for MediumJpg.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("medium_jpg")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getMediumJpg() {
        return mediumJpg;
    }

    /**
     * Setter for MediumJpg.
     * Image size information
     * @param mediumJpg Value for ImageSizeDetails
     */
    @JsonSetter("medium_jpg")
    public void setMediumJpg(ImageSizeDetails mediumJpg) {
        this.mediumJpg = mediumJpg;
    }

    /**
     * Getter for Preview.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("preview")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getPreview() {
        return preview;
    }

    /**
     * Setter for Preview.
     * Image thumbnail information
     * @param preview Value for Thumbnail
     */
    @JsonSetter("preview")
    public void setPreview(Thumbnail preview) {
        this.preview = preview;
    }

    /**
     * Getter for Preview1000.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("preview_1000")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getPreview1000() {
        return preview1000;
    }

    /**
     * Setter for Preview1000.
     * Image thumbnail information
     * @param preview1000 Value for Thumbnail
     */
    @JsonSetter("preview_1000")
    public void setPreview1000(Thumbnail preview1000) {
        this.preview1000 = preview1000;
    }

    /**
     * Getter for Preview1500.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("preview_1500")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getPreview1500() {
        return preview1500;
    }

    /**
     * Setter for Preview1500.
     * Image thumbnail information
     * @param preview1500 Value for Thumbnail
     */
    @JsonSetter("preview_1500")
    public void setPreview1500(Thumbnail preview1500) {
        this.preview1500 = preview1500;
    }

    /**
     * Getter for SmallJpg.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("small_jpg")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getSmallJpg() {
        return smallJpg;
    }

    /**
     * Setter for SmallJpg.
     * Image size information
     * @param smallJpg Value for ImageSizeDetails
     */
    @JsonSetter("small_jpg")
    public void setSmallJpg(ImageSizeDetails smallJpg) {
        this.smallJpg = smallJpg;
    }

    /**
     * Getter for SmallThumb.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("small_thumb")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getSmallThumb() {
        return smallThumb;
    }

    /**
     * Setter for SmallThumb.
     * Image thumbnail information
     * @param smallThumb Value for Thumbnail
     */
    @JsonSetter("small_thumb")
    public void setSmallThumb(Thumbnail smallThumb) {
        this.smallThumb = smallThumb;
    }

    /**
     * Getter for SupersizeJpg.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("supersize_jpg")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getSupersizeJpg() {
        return supersizeJpg;
    }

    /**
     * Setter for SupersizeJpg.
     * Image size information
     * @param supersizeJpg Value for ImageSizeDetails
     */
    @JsonSetter("supersize_jpg")
    public void setSupersizeJpg(ImageSizeDetails supersizeJpg) {
        this.supersizeJpg = supersizeJpg;
    }

    /**
     * Getter for VectorEps.
     * Image size information
     * @return Returns the ImageSizeDetails
     */
    @JsonGetter("vector_eps")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ImageSizeDetails getVectorEps() {
        return vectorEps;
    }

    /**
     * Setter for VectorEps.
     * Image size information
     * @param vectorEps Value for ImageSizeDetails
     */
    @JsonSetter("vector_eps")
    public void setVectorEps(ImageSizeDetails vectorEps) {
        this.vectorEps = vectorEps;
    }

    /**
     * Getter for Mosaic.
     * Image thumbnail information
     * @return Returns the Thumbnail
     */
    @JsonGetter("mosaic")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Thumbnail getMosaic() {
        return mosaic;
    }

    /**
     * Setter for Mosaic.
     * Image thumbnail information
     * @param mosaic Value for Thumbnail
     */
    @JsonSetter("mosaic")
    public void setMosaic(Thumbnail mosaic) {
        this.mosaic = mosaic;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ImageAssets into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ImageAssets [" + "hugeJpg=" + hugeJpg + ", hugeThumb=" + hugeThumb + ", largeThumb="
                + largeThumb + ", mediumJpg=" + mediumJpg + ", preview=" + preview
                + ", preview1000=" + preview1000 + ", preview1500=" + preview1500 + ", smallJpg="
                + smallJpg + ", smallThumb=" + smallThumb + ", supersizeJpg=" + supersizeJpg
                + ", vectorEps=" + vectorEps + ", mosaic=" + mosaic + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ImageAssets.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ImageAssets.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .hugeJpg(getHugeJpg())
                .hugeThumb(getHugeThumb())
                .largeThumb(getLargeThumb())
                .mediumJpg(getMediumJpg())
                .preview(getPreview())
                .preview1000(getPreview1000())
                .preview1500(getPreview1500())
                .smallJpg(getSmallJpg())
                .smallThumb(getSmallThumb())
                .supersizeJpg(getSupersizeJpg())
                .vectorEps(getVectorEps())
                .mosaic(getMosaic());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ImageAssets}.
     */
    public static class Builder {
        private ImageSizeDetails hugeJpg;
        private Thumbnail hugeThumb;
        private Thumbnail largeThumb;
        private ImageSizeDetails mediumJpg;
        private Thumbnail preview;
        private Thumbnail preview1000;
        private Thumbnail preview1500;
        private ImageSizeDetails smallJpg;
        private Thumbnail smallThumb;
        private ImageSizeDetails supersizeJpg;
        private ImageSizeDetails vectorEps;
        private Thumbnail mosaic;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for hugeJpg.
         * @param  hugeJpg  ImageSizeDetails value for hugeJpg.
         * @return Builder
         */
        public Builder hugeJpg(ImageSizeDetails hugeJpg) {
            this.hugeJpg = hugeJpg;
            return this;
        }

        /**
         * Setter for hugeThumb.
         * @param  hugeThumb  Thumbnail value for hugeThumb.
         * @return Builder
         */
        public Builder hugeThumb(Thumbnail hugeThumb) {
            this.hugeThumb = hugeThumb;
            return this;
        }

        /**
         * Setter for largeThumb.
         * @param  largeThumb  Thumbnail value for largeThumb.
         * @return Builder
         */
        public Builder largeThumb(Thumbnail largeThumb) {
            this.largeThumb = largeThumb;
            return this;
        }

        /**
         * Setter for mediumJpg.
         * @param  mediumJpg  ImageSizeDetails value for mediumJpg.
         * @return Builder
         */
        public Builder mediumJpg(ImageSizeDetails mediumJpg) {
            this.mediumJpg = mediumJpg;
            return this;
        }

        /**
         * Setter for preview.
         * @param  preview  Thumbnail value for preview.
         * @return Builder
         */
        public Builder preview(Thumbnail preview) {
            this.preview = preview;
            return this;
        }

        /**
         * Setter for preview1000.
         * @param  preview1000  Thumbnail value for preview1000.
         * @return Builder
         */
        public Builder preview1000(Thumbnail preview1000) {
            this.preview1000 = preview1000;
            return this;
        }

        /**
         * Setter for preview1500.
         * @param  preview1500  Thumbnail value for preview1500.
         * @return Builder
         */
        public Builder preview1500(Thumbnail preview1500) {
            this.preview1500 = preview1500;
            return this;
        }

        /**
         * Setter for smallJpg.
         * @param  smallJpg  ImageSizeDetails value for smallJpg.
         * @return Builder
         */
        public Builder smallJpg(ImageSizeDetails smallJpg) {
            this.smallJpg = smallJpg;
            return this;
        }

        /**
         * Setter for smallThumb.
         * @param  smallThumb  Thumbnail value for smallThumb.
         * @return Builder
         */
        public Builder smallThumb(Thumbnail smallThumb) {
            this.smallThumb = smallThumb;
            return this;
        }

        /**
         * Setter for supersizeJpg.
         * @param  supersizeJpg  ImageSizeDetails value for supersizeJpg.
         * @return Builder
         */
        public Builder supersizeJpg(ImageSizeDetails supersizeJpg) {
            this.supersizeJpg = supersizeJpg;
            return this;
        }

        /**
         * Setter for vectorEps.
         * @param  vectorEps  ImageSizeDetails value for vectorEps.
         * @return Builder
         */
        public Builder vectorEps(ImageSizeDetails vectorEps) {
            this.vectorEps = vectorEps;
            return this;
        }

        /**
         * Setter for mosaic.
         * @param  mosaic  Thumbnail value for mosaic.
         * @return Builder
         */
        public Builder mosaic(Thumbnail mosaic) {
            this.mosaic = mosaic;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ImageAssets} object using the set fields.
         * @return {@link ImageAssets}
         */
        public ImageAssets build() {
            ImageAssets model =
                    new ImageAssets(hugeJpg, hugeThumb, largeThumb, mediumJpg, preview, preview1000,
                            preview1500, smallJpg, smallThumb, supersizeJpg, vectorEps, mosaic);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
