/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Image type.
 */
public class Image {
    private LocalDate addedDate;
    private String affiliateUrl;
    private Double aspect;
    private Assets3 assets;
    private List<Category> categories;
    private Contributor contributor;
    private String description;
    private Boolean hasModelRelease;
    private Boolean hasPropertyRelease;
    private String id;
    private String imageType;
    private Boolean isAdult;
    private Boolean isEditorial;
    private Boolean isIllustration;
    private List<String> keywords;
    private String mediaType;
    private List<ModelRelease> modelReleases;
    private List<Model> models;
    private List<String> releases;
    private String url;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Image() {
    }

    /**
     * Initialization constructor.
     * @param  contributor  Contributor value for contributor.
     * @param  id  String value for id.
     * @param  mediaType  String value for mediaType.
     * @param  addedDate  LocalDate value for addedDate.
     * @param  affiliateUrl  String value for affiliateUrl.
     * @param  aspect  Double value for aspect.
     * @param  assets  Assets3 value for assets.
     * @param  categories  List of Category value for categories.
     * @param  description  String value for description.
     * @param  hasModelRelease  Boolean value for hasModelRelease.
     * @param  hasPropertyRelease  Boolean value for hasPropertyRelease.
     * @param  imageType  String value for imageType.
     * @param  isAdult  Boolean value for isAdult.
     * @param  isEditorial  Boolean value for isEditorial.
     * @param  isIllustration  Boolean value for isIllustration.
     * @param  keywords  List of String value for keywords.
     * @param  modelReleases  List of ModelRelease value for modelReleases.
     * @param  models  List of Model value for models.
     * @param  releases  List of String value for releases.
     * @param  url  String value for url.
     */
    public Image(
            Contributor contributor,
            String id,
            String mediaType,
            LocalDate addedDate,
            String affiliateUrl,
            Double aspect,
            Assets3 assets,
            List<Category> categories,
            String description,
            Boolean hasModelRelease,
            Boolean hasPropertyRelease,
            String imageType,
            Boolean isAdult,
            Boolean isEditorial,
            Boolean isIllustration,
            List<String> keywords,
            List<ModelRelease> modelReleases,
            List<Model> models,
            List<String> releases,
            String url) {
        this.addedDate = addedDate;
        this.affiliateUrl = affiliateUrl;
        this.aspect = aspect;
        this.assets = assets;
        this.categories = categories;
        this.contributor = contributor;
        this.description = description;
        this.hasModelRelease = hasModelRelease;
        this.hasPropertyRelease = hasPropertyRelease;
        this.id = id;
        this.imageType = imageType;
        this.isAdult = isAdult;
        this.isEditorial = isEditorial;
        this.isIllustration = isIllustration;
        this.keywords = keywords;
        this.mediaType = mediaType;
        this.modelReleases = modelReleases;
        this.models = models;
        this.releases = releases;
        this.url = url;
    }

    /**
     * Getter for AddedDate.
     * Date that the image was added by the contributor
     * @return Returns the LocalDate
     */
    @JsonGetter("added_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getAddedDate() {
        return addedDate;
    }

    /**
     * Setter for AddedDate.
     * Date that the image was added by the contributor
     * @param addedDate Value for LocalDate
     */
    @JsonSetter("added_date")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setAddedDate(LocalDate addedDate) {
        this.addedDate = addedDate;
    }

    /**
     * Getter for AffiliateUrl.
     * Affiliate referral link; appears only for registered affiliate partners
     * @return Returns the String
     */
    @JsonGetter("affiliate_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAffiliateUrl() {
        return affiliateUrl;
    }

    /**
     * Setter for AffiliateUrl.
     * Affiliate referral link; appears only for registered affiliate partners
     * @param affiliateUrl Value for String
     */
    @JsonSetter("affiliate_url")
    public void setAffiliateUrl(String affiliateUrl) {
        this.affiliateUrl = affiliateUrl;
    }

    /**
     * Getter for Aspect.
     * Aspect ratio of the image in decimal format, such as 0.6667
     * @return Returns the Double
     */
    @JsonGetter("aspect")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAspect() {
        return aspect;
    }

    /**
     * Setter for Aspect.
     * Aspect ratio of the image in decimal format, such as 0.6667
     * @param aspect Value for Double
     */
    @JsonSetter("aspect")
    public void setAspect(Double aspect) {
        this.aspect = aspect;
    }

    /**
     * Getter for Assets.
     * Image asset information
     * @return Returns the Assets3
     */
    @JsonGetter("assets")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Assets3 getAssets() {
        return assets;
    }

    /**
     * Setter for Assets.
     * Image asset information
     * @param assets Value for Assets3
     */
    @JsonSetter("assets")
    public void setAssets(Assets3 assets) {
        this.assets = assets;
    }

    /**
     * Getter for Categories.
     * Categories that this image is a part of
     * @return Returns the List of Category
     */
    @JsonGetter("categories")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Category> getCategories() {
        return categories;
    }

    /**
     * Setter for Categories.
     * Categories that this image is a part of
     * @param categories Value for List of Category
     */
    @JsonSetter("categories")
    public void setCategories(List<Category> categories) {
        this.categories = categories;
    }

    /**
     * Getter for Contributor.
     * Information about a contributor
     * @return Returns the Contributor
     */
    @JsonGetter("contributor")
    public Contributor getContributor() {
        return contributor;
    }

    /**
     * Setter for Contributor.
     * Information about a contributor
     * @param contributor Value for Contributor
     */
    @JsonSetter("contributor")
    public void setContributor(Contributor contributor) {
        this.contributor = contributor;
    }

    /**
     * Getter for Description.
     * Detailed description of the image
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Detailed description of the image
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for HasModelRelease.
     * Indicates whether there are model releases for the image
     * @return Returns the Boolean
     */
    @JsonGetter("has_model_release")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getHasModelRelease() {
        return hasModelRelease;
    }

    /**
     * Setter for HasModelRelease.
     * Indicates whether there are model releases for the image
     * @param hasModelRelease Value for Boolean
     */
    @JsonSetter("has_model_release")
    public void setHasModelRelease(Boolean hasModelRelease) {
        this.hasModelRelease = hasModelRelease;
    }

    /**
     * Getter for HasPropertyRelease.
     * Indicates whether there are property releases for the image
     * @return Returns the Boolean
     */
    @JsonGetter("has_property_release")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getHasPropertyRelease() {
        return hasPropertyRelease;
    }

    /**
     * Setter for HasPropertyRelease.
     * Indicates whether there are property releases for the image
     * @param hasPropertyRelease Value for Boolean
     */
    @JsonSetter("has_property_release")
    public void setHasPropertyRelease(Boolean hasPropertyRelease) {
        this.hasPropertyRelease = hasPropertyRelease;
    }

    /**
     * Getter for Id.
     * Image ID
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Image ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for ImageType.
     * Type of image
     * @return Returns the String
     */
    @JsonGetter("image_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getImageType() {
        return imageType;
    }

    /**
     * Setter for ImageType.
     * Type of image
     * @param imageType Value for String
     */
    @JsonSetter("image_type")
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }

    /**
     * Getter for IsAdult.
     * Whether or not this image contains adult content
     * @return Returns the Boolean
     */
    @JsonGetter("is_adult")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsAdult() {
        return isAdult;
    }

    /**
     * Setter for IsAdult.
     * Whether or not this image contains adult content
     * @param isAdult Value for Boolean
     */
    @JsonSetter("is_adult")
    public void setIsAdult(Boolean isAdult) {
        this.isAdult = isAdult;
    }

    /**
     * Getter for IsEditorial.
     * Whether or not this image is editorial content
     * @return Returns the Boolean
     */
    @JsonGetter("is_editorial")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsEditorial() {
        return isEditorial;
    }

    /**
     * Setter for IsEditorial.
     * Whether or not this image is editorial content
     * @param isEditorial Value for Boolean
     */
    @JsonSetter("is_editorial")
    public void setIsEditorial(Boolean isEditorial) {
        this.isEditorial = isEditorial;
    }

    /**
     * Getter for IsIllustration.
     * Whether or not this image is an illustration
     * @return Returns the Boolean
     */
    @JsonGetter("is_illustration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsIllustration() {
        return isIllustration;
    }

    /**
     * Setter for IsIllustration.
     * Whether or not this image is an illustration
     * @param isIllustration Value for Boolean
     */
    @JsonSetter("is_illustration")
    public void setIsIllustration(Boolean isIllustration) {
        this.isIllustration = isIllustration;
    }

    /**
     * Getter for Keywords.
     * Keywords associated with the content of this image
     * @return Returns the List of String
     */
    @JsonGetter("keywords")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getKeywords() {
        return keywords;
    }

    /**
     * Setter for Keywords.
     * Keywords associated with the content of this image
     * @param keywords Value for List of String
     */
    @JsonSetter("keywords")
    public void setKeywords(List<String> keywords) {
        this.keywords = keywords;
    }

    /**
     * Getter for MediaType.
     * Media type of this image, should always be "image"
     * @return Returns the String
     */
    @JsonGetter("media_type")
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Setter for MediaType.
     * Media type of this image, should always be "image"
     * @param mediaType Value for String
     */
    @JsonSetter("media_type")
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * Getter for ModelReleases.
     * List of model releases
     * @return Returns the List of ModelRelease
     */
    @JsonGetter("model_releases")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ModelRelease> getModelReleases() {
        return modelReleases;
    }

    /**
     * Setter for ModelReleases.
     * List of model releases
     * @param modelReleases Value for List of ModelRelease
     */
    @JsonSetter("model_releases")
    public void setModelReleases(List<ModelRelease> modelReleases) {
        this.modelReleases = modelReleases;
    }

    /**
     * Getter for Models.
     * List of models
     * @return Returns the List of Model
     */
    @JsonGetter("models")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Model> getModels() {
        return models;
    }

    /**
     * Setter for Models.
     * List of models
     * @param models Value for List of Model
     */
    @JsonSetter("models")
    public void setModels(List<Model> models) {
        this.models = models;
    }

    /**
     * Getter for Releases.
     * List of all releases of this image
     * @return Returns the List of String
     */
    @JsonGetter("releases")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getReleases() {
        return releases;
    }

    /**
     * Setter for Releases.
     * List of all releases of this image
     * @param releases Value for List of String
     */
    @JsonSetter("releases")
    public void setReleases(List<String> releases) {
        this.releases = releases;
    }

    /**
     * Getter for Url.
     * Link to image information page; included only for certain accounts
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * Link to image information page; included only for certain accounts
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Image into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Image [" + "contributor=" + contributor + ", id=" + id + ", mediaType=" + mediaType
                + ", addedDate=" + addedDate + ", affiliateUrl=" + affiliateUrl + ", aspect="
                + aspect + ", assets=" + assets + ", categories=" + categories + ", description="
                + description + ", hasModelRelease=" + hasModelRelease + ", hasPropertyRelease="
                + hasPropertyRelease + ", imageType=" + imageType + ", isAdult=" + isAdult
                + ", isEditorial=" + isEditorial + ", isIllustration=" + isIllustration
                + ", keywords=" + keywords + ", modelReleases=" + modelReleases + ", models="
                + models + ", releases=" + releases + ", url=" + url + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Image.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Image.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(contributor, id, mediaType)
                .addedDate(getAddedDate())
                .affiliateUrl(getAffiliateUrl())
                .aspect(getAspect())
                .assets(getAssets())
                .categories(getCategories())
                .description(getDescription())
                .hasModelRelease(getHasModelRelease())
                .hasPropertyRelease(getHasPropertyRelease())
                .imageType(getImageType())
                .isAdult(getIsAdult())
                .isEditorial(getIsEditorial())
                .isIllustration(getIsIllustration())
                .keywords(getKeywords())
                .modelReleases(getModelReleases())
                .models(getModels())
                .releases(getReleases())
                .url(getUrl());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Image}.
     */
    public static class Builder {
        private Contributor contributor;
        private String id;
        private String mediaType;
        private LocalDate addedDate;
        private String affiliateUrl;
        private Double aspect;
        private Assets3 assets;
        private List<Category> categories;
        private String description;
        private Boolean hasModelRelease;
        private Boolean hasPropertyRelease;
        private String imageType;
        private Boolean isAdult;
        private Boolean isEditorial;
        private Boolean isIllustration;
        private List<String> keywords;
        private List<ModelRelease> modelReleases;
        private List<Model> models;
        private List<String> releases;
        private String url;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  contributor  Contributor value for contributor.
         * @param  id  String value for id.
         * @param  mediaType  String value for mediaType.
         */
        public Builder(Contributor contributor, String id, String mediaType) {
            this.contributor = contributor;
            this.id = id;
            this.mediaType = mediaType;
        }

        /**
         * Setter for contributor.
         * @param  contributor  Contributor value for contributor.
         * @return Builder
         */
        public Builder contributor(Contributor contributor) {
            this.contributor = contributor;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for mediaType.
         * @param  mediaType  String value for mediaType.
         * @return Builder
         */
        public Builder mediaType(String mediaType) {
            this.mediaType = mediaType;
            return this;
        }

        /**
         * Setter for addedDate.
         * @param  addedDate  LocalDate value for addedDate.
         * @return Builder
         */
        public Builder addedDate(LocalDate addedDate) {
            this.addedDate = addedDate;
            return this;
        }

        /**
         * Setter for affiliateUrl.
         * @param  affiliateUrl  String value for affiliateUrl.
         * @return Builder
         */
        public Builder affiliateUrl(String affiliateUrl) {
            this.affiliateUrl = affiliateUrl;
            return this;
        }

        /**
         * Setter for aspect.
         * @param  aspect  Double value for aspect.
         * @return Builder
         */
        public Builder aspect(Double aspect) {
            this.aspect = aspect;
            return this;
        }

        /**
         * Setter for assets.
         * @param  assets  Assets3 value for assets.
         * @return Builder
         */
        public Builder assets(Assets3 assets) {
            this.assets = assets;
            return this;
        }

        /**
         * Setter for categories.
         * @param  categories  List of Category value for categories.
         * @return Builder
         */
        public Builder categories(List<Category> categories) {
            this.categories = categories;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for hasModelRelease.
         * @param  hasModelRelease  Boolean value for hasModelRelease.
         * @return Builder
         */
        public Builder hasModelRelease(Boolean hasModelRelease) {
            this.hasModelRelease = hasModelRelease;
            return this;
        }

        /**
         * Setter for hasPropertyRelease.
         * @param  hasPropertyRelease  Boolean value for hasPropertyRelease.
         * @return Builder
         */
        public Builder hasPropertyRelease(Boolean hasPropertyRelease) {
            this.hasPropertyRelease = hasPropertyRelease;
            return this;
        }

        /**
         * Setter for imageType.
         * @param  imageType  String value for imageType.
         * @return Builder
         */
        public Builder imageType(String imageType) {
            this.imageType = imageType;
            return this;
        }

        /**
         * Setter for isAdult.
         * @param  isAdult  Boolean value for isAdult.
         * @return Builder
         */
        public Builder isAdult(Boolean isAdult) {
            this.isAdult = isAdult;
            return this;
        }

        /**
         * Setter for isEditorial.
         * @param  isEditorial  Boolean value for isEditorial.
         * @return Builder
         */
        public Builder isEditorial(Boolean isEditorial) {
            this.isEditorial = isEditorial;
            return this;
        }

        /**
         * Setter for isIllustration.
         * @param  isIllustration  Boolean value for isIllustration.
         * @return Builder
         */
        public Builder isIllustration(Boolean isIllustration) {
            this.isIllustration = isIllustration;
            return this;
        }

        /**
         * Setter for keywords.
         * @param  keywords  List of String value for keywords.
         * @return Builder
         */
        public Builder keywords(List<String> keywords) {
            this.keywords = keywords;
            return this;
        }

        /**
         * Setter for modelReleases.
         * @param  modelReleases  List of ModelRelease value for modelReleases.
         * @return Builder
         */
        public Builder modelReleases(List<ModelRelease> modelReleases) {
            this.modelReleases = modelReleases;
            return this;
        }

        /**
         * Setter for models.
         * @param  models  List of Model value for models.
         * @return Builder
         */
        public Builder models(List<Model> models) {
            this.models = models;
            return this;
        }

        /**
         * Setter for releases.
         * @param  releases  List of String value for releases.
         * @return Builder
         */
        public Builder releases(List<String> releases) {
            this.releases = releases;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Image} object using the set fields.
         * @return {@link Image}
         */
        public Image build() {
            Image model =
                    new Image(contributor, id, mediaType, addedDate, affiliateUrl, aspect, assets,
                            categories, description, hasModelRelease, hasPropertyRelease, imageType,
                            isAdult, isEditorial, isIllustration, keywords, modelReleases, models,
                            releases, url);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
