/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * License10 to be used.
 */
public enum License10 {
    AUDIO_PLATFORM,

    PREMIER_MUSIC_BASIC,

    PREMIER_MUSIC_EXTENDED,

    PREMIER_MUSIC_PRO,

    PREMIER_MUSIC_COMP,

    ASSET_ALL_MUSIC;

    private static TreeMap<String, License10> valueMap = new TreeMap<>();
    private String value;

    static {
        AUDIO_PLATFORM.value = "audio_platform";
        PREMIER_MUSIC_BASIC.value = "premier_music_basic";
        PREMIER_MUSIC_EXTENDED.value = "premier_music_extended";
        PREMIER_MUSIC_PRO.value = "premier_music_pro";
        PREMIER_MUSIC_COMP.value = "premier_music_comp";
        ASSET_ALL_MUSIC.value = "asset_all_music";

        valueMap.put("audio_platform", AUDIO_PLATFORM);
        valueMap.put("premier_music_basic", PREMIER_MUSIC_BASIC);
        valueMap.put("premier_music_extended", PREMIER_MUSIC_EXTENDED);
        valueMap.put("premier_music_pro", PREMIER_MUSIC_PRO);
        valueMap.put("premier_music_comp", PREMIER_MUSIC_COMP);
        valueMap.put("asset_all_music", ASSET_ALL_MUSIC);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static License10 constructFromString(String toConvert) throws IOException {
        License10 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static License10 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of License10 values to list of string values.
     * @param toConvert The list of License10 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<License10> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (License10 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 