/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for LicenseEditorialContentResult type.
 */
public class LicenseEditorialContentResult {
    private Integer allotmentCharge;
    private Download2 download;
    private String editorialId;
    private String error;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LicenseEditorialContentResult() {
    }

    /**
     * Initialization constructor.
     * @param  editorialId  String value for editorialId.
     * @param  allotmentCharge  Integer value for allotmentCharge.
     * @param  download  Download2 value for download.
     * @param  error  String value for error.
     */
    public LicenseEditorialContentResult(
            String editorialId,
            Integer allotmentCharge,
            Download2 download,
            String error) {
        this.allotmentCharge = allotmentCharge;
        this.download = download;
        this.editorialId = editorialId;
        this.error = error;
    }

    /**
     * Getter for AllotmentCharge.
     * For pre-paid plans, how many credits were used for the item license
     * @return Returns the Integer
     */
    @JsonGetter("allotment_charge")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAllotmentCharge() {
        return allotmentCharge;
    }

    /**
     * Setter for AllotmentCharge.
     * For pre-paid plans, how many credits were used for the item license
     * @param allotmentCharge Value for Integer
     */
    @JsonSetter("allotment_charge")
    public void setAllotmentCharge(Integer allotmentCharge) {
        this.allotmentCharge = allotmentCharge;
    }

    /**
     * Getter for Download.
     * Information that is needed to download the image
     * @return Returns the Download2
     */
    @JsonGetter("download")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Download2 getDownload() {
        return download;
    }

    /**
     * Setter for Download.
     * Information that is needed to download the image
     * @param download Value for Download2
     */
    @JsonSetter("download")
    public void setDownload(Download2 download) {
        this.download = download;
    }

    /**
     * Getter for EditorialId.
     * Editorial ID
     * @return Returns the String
     */
    @JsonGetter("editorial_id")
    public String getEditorialId() {
        return editorialId;
    }

    /**
     * Setter for EditorialId.
     * Editorial ID
     * @param editorialId Value for String
     */
    @JsonSetter("editorial_id")
    public void setEditorialId(String editorialId) {
        this.editorialId = editorialId;
    }

    /**
     * Getter for Error.
     * @return Returns the String
     */
    @JsonGetter("error")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getError() {
        return error;
    }

    /**
     * Setter for Error.
     * @param error Value for String
     */
    @JsonSetter("error")
    public void setError(String error) {
        this.error = error;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LicenseEditorialContentResult into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LicenseEditorialContentResult [" + "editorialId=" + editorialId
                + ", allotmentCharge=" + allotmentCharge + ", download=" + download + ", error="
                + error + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LicenseEditorialContentResult.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LicenseEditorialContentResult.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(editorialId)
                .allotmentCharge(getAllotmentCharge())
                .download(getDownload())
                .error(getError());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LicenseEditorialContentResult}.
     */
    public static class Builder {
        private String editorialId;
        private Integer allotmentCharge;
        private Download2 download;
        private String error;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  editorialId  String value for editorialId.
         */
        public Builder(String editorialId) {
            this.editorialId = editorialId;
        }

        /**
         * Setter for editorialId.
         * @param  editorialId  String value for editorialId.
         * @return Builder
         */
        public Builder editorialId(String editorialId) {
            this.editorialId = editorialId;
            return this;
        }

        /**
         * Setter for allotmentCharge.
         * @param  allotmentCharge  Integer value for allotmentCharge.
         * @return Builder
         */
        public Builder allotmentCharge(Integer allotmentCharge) {
            this.allotmentCharge = allotmentCharge;
            return this;
        }

        /**
         * Setter for download.
         * @param  download  Download2 value for download.
         * @return Builder
         */
        public Builder download(Download2 download) {
            this.download = download;
            return this;
        }

        /**
         * Setter for error.
         * @param  error  String value for error.
         * @return Builder
         */
        public Builder error(String error) {
            this.error = error;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LicenseEditorialContentResult} object using the set fields.
         * @return {@link LicenseEditorialContentResult}
         */
        public LicenseEditorialContentResult build() {
            LicenseEditorialContentResult model =
                    new LicenseEditorialContentResult(editorialId, allotmentCharge, download,
                            error);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
