/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * License3 to be used.
 */
public enum License3 {
    PREMIER_EDITORIAL_VIDEO_DIGITAL_ONLY,

    PREMIER_EDITORIAL_VIDEO_ALL_MEDIA,

    PREMIER_EDITORIAL_VIDEO_ALL_MEDIA_SINGLE_TERRITORY,

    PREMIER_EDITORIAL_VIDEO_COMP;

    private static TreeMap<String, License3> valueMap = new TreeMap<>();
    private String value;

    static {
        PREMIER_EDITORIAL_VIDEO_DIGITAL_ONLY.value = "premier_editorial_video_digital_only";
        PREMIER_EDITORIAL_VIDEO_ALL_MEDIA.value = "premier_editorial_video_all_media";
        PREMIER_EDITORIAL_VIDEO_ALL_MEDIA_SINGLE_TERRITORY.value = "premier_editorial_video_all_media_single_territory";
        PREMIER_EDITORIAL_VIDEO_COMP.value = "premier_editorial_video_comp";

        valueMap.put("premier_editorial_video_digital_only", PREMIER_EDITORIAL_VIDEO_DIGITAL_ONLY);
        valueMap.put("premier_editorial_video_all_media", PREMIER_EDITORIAL_VIDEO_ALL_MEDIA);
        valueMap.put("premier_editorial_video_all_media_single_territory", PREMIER_EDITORIAL_VIDEO_ALL_MEDIA_SINGLE_TERRITORY);
        valueMap.put("premier_editorial_video_comp", PREMIER_EDITORIAL_VIDEO_COMP);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static License3 constructFromString(String toConvert) throws IOException {
        License3 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static License3 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of License3 values to list of string values.
     * @param toConvert The list of License3 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<License3> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (License3 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 