/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for LicenseSfx type.
 */
public class LicenseSfx {
    private String sfxId;
    private AudioLayout audioLayout;
    private Format11 format;
    private String searchId;
    private String subscriptionId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LicenseSfx() {
    }

    /**
     * Initialization constructor.
     * @param  sfxId  String value for sfxId.
     * @param  subscriptionId  String value for subscriptionId.
     * @param  audioLayout  AudioLayout value for audioLayout.
     * @param  format  Format11 value for format.
     * @param  searchId  String value for searchId.
     */
    public LicenseSfx(
            String sfxId,
            String subscriptionId,
            AudioLayout audioLayout,
            Format11 format,
            String searchId) {
        this.sfxId = sfxId;
        this.audioLayout = audioLayout;
        this.format = format;
        this.searchId = searchId;
        this.subscriptionId = subscriptionId;
    }

    /**
     * Getter for SfxId.
     * ID of the sounds effect being licensed
     * @return Returns the String
     */
    @JsonGetter("sfx_id")
    public String getSfxId() {
        return sfxId;
    }

    /**
     * Setter for SfxId.
     * ID of the sounds effect being licensed
     * @param sfxId Value for String
     */
    @JsonSetter("sfx_id")
    public void setSfxId(String sfxId) {
        this.sfxId = sfxId;
    }

    /**
     * Getter for AudioLayout.
     * @return Returns the AudioLayout
     */
    @JsonGetter("audio_layout")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AudioLayout getAudioLayout() {
        return audioLayout;
    }

    /**
     * Setter for AudioLayout.
     * @param audioLayout Value for AudioLayout
     */
    @JsonSetter("audio_layout")
    public void setAudioLayout(AudioLayout audioLayout) {
        this.audioLayout = audioLayout;
    }

    /**
     * Getter for Format.
     * @return Returns the Format11
     */
    @JsonGetter("format")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Format11 getFormat() {
        return format;
    }

    /**
     * Setter for Format.
     * @param format Value for Format11
     */
    @JsonSetter("format")
    public void setFormat(Format11 format) {
        this.format = format;
    }

    /**
     * Getter for SearchId.
     * ID of the search that led to this licensing event
     * @return Returns the String
     */
    @JsonGetter("search_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSearchId() {
        return searchId;
    }

    /**
     * Setter for SearchId.
     * ID of the search that led to this licensing event
     * @param searchId Value for String
     */
    @JsonSetter("search_id")
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * Getter for SubscriptionId.
     * ID of the subscription to use for the download.
     * @return Returns the String
     */
    @JsonGetter("subscription_id")
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Setter for SubscriptionId.
     * ID of the subscription to use for the download.
     * @param subscriptionId Value for String
     */
    @JsonSetter("subscription_id")
    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LicenseSfx into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LicenseSfx [" + "sfxId=" + sfxId + ", subscriptionId=" + subscriptionId
                + ", audioLayout=" + audioLayout + ", format=" + format + ", searchId=" + searchId
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LicenseSfx.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LicenseSfx.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(sfxId, subscriptionId)
                .audioLayout(getAudioLayout())
                .format(getFormat())
                .searchId(getSearchId());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LicenseSfx}.
     */
    public static class Builder {
        private String sfxId;
        private String subscriptionId;
        private AudioLayout audioLayout;
        private Format11 format;
        private String searchId;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  sfxId  String value for sfxId.
         * @param  subscriptionId  String value for subscriptionId.
         */
        public Builder(String sfxId, String subscriptionId) {
            this.sfxId = sfxId;
            this.subscriptionId = subscriptionId;
        }

        /**
         * Setter for sfxId.
         * @param  sfxId  String value for sfxId.
         * @return Builder
         */
        public Builder sfxId(String sfxId) {
            this.sfxId = sfxId;
            return this;
        }

        /**
         * Setter for subscriptionId.
         * @param  subscriptionId  String value for subscriptionId.
         * @return Builder
         */
        public Builder subscriptionId(String subscriptionId) {
            this.subscriptionId = subscriptionId;
            return this;
        }

        /**
         * Setter for audioLayout.
         * @param  audioLayout  AudioLayout value for audioLayout.
         * @return Builder
         */
        public Builder audioLayout(AudioLayout audioLayout) {
            this.audioLayout = audioLayout;
            return this;
        }

        /**
         * Setter for format.
         * @param  format  Format11 value for format.
         * @return Builder
         */
        public Builder format(Format11 format) {
            this.format = format;
            return this;
        }

        /**
         * Setter for searchId.
         * @param  searchId  String value for searchId.
         * @return Builder
         */
        public Builder searchId(String searchId) {
            this.searchId = searchId;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LicenseSfx} object using the set fields.
         * @return {@link LicenseSfx}
         */
        public LicenseSfx build() {
            LicenseSfx model =
                    new LicenseSfx(sfxId, subscriptionId, audioLayout, format, searchId);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
