/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for LicenseSfxRequest type.
 */
public class LicenseSfxRequest {
    private List<LicenseSfx> soundEffects;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LicenseSfxRequest() {
    }

    /**
     * Initialization constructor.
     * @param  soundEffects  List of LicenseSfx value for soundEffects.
     */
    public LicenseSfxRequest(
            List<LicenseSfx> soundEffects) {
        this.soundEffects = soundEffects;
    }

    /**
     * Getter for SoundEffects.
     * Sound effects to license for
     * @return Returns the List of LicenseSfx
     */
    @JsonGetter("sound_effects")
    public List<LicenseSfx> getSoundEffects() {
        return soundEffects;
    }

    /**
     * Setter for SoundEffects.
     * Sound effects to license for
     * @param soundEffects Value for List of LicenseSfx
     */
    @JsonSetter("sound_effects")
    public void setSoundEffects(List<LicenseSfx> soundEffects) {
        this.soundEffects = soundEffects;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LicenseSfxRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LicenseSfxRequest [" + "soundEffects=" + soundEffects + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LicenseSfxRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LicenseSfxRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(soundEffects);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LicenseSfxRequest}.
     */
    public static class Builder {
        private List<LicenseSfx> soundEffects;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  soundEffects  List of LicenseSfx value for soundEffects.
         */
        public Builder(List<LicenseSfx> soundEffects) {
            this.soundEffects = soundEffects;
        }

        /**
         * Setter for soundEffects.
         * @param  soundEffects  List of LicenseSfx value for soundEffects.
         * @return Builder
         */
        public Builder soundEffects(List<LicenseSfx> soundEffects) {
            this.soundEffects = soundEffects;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LicenseSfxRequest} object using the set fields.
         * @return {@link LicenseSfxRequest}
         */
        public LicenseSfxRequest build() {
            LicenseSfxRequest model =
                    new LicenseSfxRequest(soundEffects);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
