/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for LicenseAudioRequest type.
 */
public class LicenseAudioRequest {
    private List<LicenseAudio> audio;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LicenseAudioRequest() {
    }

    /**
     * Initialization constructor.
     * @param  audio  List of LicenseAudio value for audio.
     */
    public LicenseAudioRequest(
            List<LicenseAudio> audio) {
        this.audio = audio;
    }

    /**
     * Getter for Audio.
     * List of audio tracks to license
     * @return Returns the List of LicenseAudio
     */
    @JsonGetter("audio")
    public List<LicenseAudio> getAudio() {
        return audio;
    }

    /**
     * Setter for Audio.
     * List of audio tracks to license
     * @param audio Value for List of LicenseAudio
     */
    @JsonSetter("audio")
    public void setAudio(List<LicenseAudio> audio) {
        this.audio = audio;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LicenseAudioRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LicenseAudioRequest [" + "audio=" + audio + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LicenseAudioRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LicenseAudioRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(audio);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LicenseAudioRequest}.
     */
    public static class Builder {
        private List<LicenseAudio> audio;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  audio  List of LicenseAudio value for audio.
         */
        public Builder(List<LicenseAudio> audio) {
            this.audio = audio;
        }

        /**
         * Setter for audio.
         * @param  audio  List of LicenseAudio value for audio.
         * @return Builder
         */
        public Builder audio(List<LicenseAudio> audio) {
            this.audio = audio;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LicenseAudioRequest} object using the set fields.
         * @return {@link LicenseAudioRequest}
         */
        public LicenseAudioRequest build() {
            LicenseAudioRequest model =
                    new LicenseAudioRequest(audio);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
