/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for LicenseVideoRequest type.
 */
public class LicenseVideoRequest {
    private List<LicenseVideo> videos;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LicenseVideoRequest() {
    }

    /**
     * Initialization constructor.
     * @param  videos  List of LicenseVideo value for videos.
     */
    public LicenseVideoRequest(
            List<LicenseVideo> videos) {
        this.videos = videos;
    }

    /**
     * Getter for Videos.
     * Videos to license
     * @return Returns the List of LicenseVideo
     */
    @JsonGetter("videos")
    public List<LicenseVideo> getVideos() {
        return videos;
    }

    /**
     * Setter for Videos.
     * Videos to license
     * @param videos Value for List of LicenseVideo
     */
    @JsonSetter("videos")
    public void setVideos(List<LicenseVideo> videos) {
        this.videos = videos;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LicenseVideoRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LicenseVideoRequest [" + "videos=" + videos + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LicenseVideoRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LicenseVideoRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(videos);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LicenseVideoRequest}.
     */
    public static class Builder {
        private List<LicenseVideo> videos;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  videos  List of LicenseVideo value for videos.
         */
        public Builder(List<LicenseVideo> videos) {
            this.videos = videos;
        }

        /**
         * Setter for videos.
         * @param  videos  List of LicenseVideo value for videos.
         * @return Builder
         */
        public Builder videos(List<LicenseVideo> videos) {
            this.videos = videos;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LicenseVideoRequest} object using the set fields.
         * @return {@link LicenseVideoRequest}
         */
        public LicenseVideoRequest build() {
            LicenseVideoRequest model =
                    new LicenseVideoRequest(videos);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
