/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * MediaType to be used.
 */
public enum MediaType {
    IMAGE,

    VIDEO,

    AUDIO,

    EDITORIAL;

    private static TreeMap<String, MediaType> valueMap = new TreeMap<>();
    private String value;

    static {
        IMAGE.value = "image";
        VIDEO.value = "video";
        AUDIO.value = "audio";
        EDITORIAL.value = "editorial";

        valueMap.put("image", IMAGE);
        valueMap.put("video", VIDEO);
        valueMap.put("audio", AUDIO);
        valueMap.put("editorial", EDITORIAL);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static MediaType constructFromString(String toConvert) throws IOException {
        MediaType enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static MediaType fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of MediaType values to list of string values.
     * @param toConvert The list of MediaType values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<MediaType> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (MediaType enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 