/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * PeopleGender to be used.
 */
public enum PeopleGender {
    MALE,

    FEMALE,

    BOTH;

    private static TreeMap<String, PeopleGender> valueMap = new TreeMap<>();
    private String value;

    static {
        MALE.value = "male";
        FEMALE.value = "female";
        BOTH.value = "both";

        valueMap.put("male", MALE);
        valueMap.put("female", FEMALE);
        valueMap.put("both", BOTH);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PeopleGender constructFromString(String toConvert) throws IOException {
        PeopleGender enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PeopleGender fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PeopleGender values to list of string values.
     * @param toConvert The list of PeopleGender values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PeopleGender> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PeopleGender enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 