/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Realm2 to be used.
 */
public enum Realm2 {
    CUSTOMER,

    CONTRIBUTOR;

    private static TreeMap<String, Realm2> valueMap = new TreeMap<>();
    private String value;

    static {
        CUSTOMER.value = "customer";
        CONTRIBUTOR.value = "contributor";

        valueMap.put("customer", CUSTOMER);
        valueMap.put("contributor", CONTRIBUTOR);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Realm2 constructFromString(String toConvert) throws IOException {
        Realm2 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Realm2 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Realm2 values to list of string values.
     * @param toConvert The list of Realm2 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Realm2> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Realm2 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 