/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for RedownloadImage type.
 */
public class RedownloadImage {
    private AuthCookie6 authCookie;
    private Boolean showModal;
    private Size10 size;
    private String verificationCode;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public RedownloadImage() {
    }

    /**
     * Initialization constructor.
     * @param  authCookie  AuthCookie6 value for authCookie.
     * @param  showModal  Boolean value for showModal.
     * @param  size  Size10 value for size.
     * @param  verificationCode  String value for verificationCode.
     */
    public RedownloadImage(
            AuthCookie6 authCookie,
            Boolean showModal,
            Size10 size,
            String verificationCode) {
        this.authCookie = authCookie;
        this.showModal = showModal;
        this.size = size;
        this.verificationCode = verificationCode;
    }

    /**
     * Getter for AuthCookie.
     * (Deprecated)
     * @return Returns the AuthCookie6
     */
    @JsonGetter("auth_cookie")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AuthCookie6 getAuthCookie() {
        return authCookie;
    }

    /**
     * Setter for AuthCookie.
     * (Deprecated)
     * @param authCookie Value for AuthCookie6
     */
    @JsonSetter("auth_cookie")
    public void setAuthCookie(AuthCookie6 authCookie) {
        this.authCookie = authCookie;
    }

    /**
     * Getter for ShowModal.
     * (Deprecated)
     * @return Returns the Boolean
     */
    @JsonGetter("show_modal")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getShowModal() {
        return showModal;
    }

    /**
     * Setter for ShowModal.
     * (Deprecated)
     * @param showModal Value for Boolean
     */
    @JsonSetter("show_modal")
    public void setShowModal(Boolean showModal) {
        this.showModal = showModal;
    }

    /**
     * Getter for Size.
     * Size of the image
     * @return Returns the Size10
     */
    @JsonGetter("size")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Size10 getSize() {
        return size;
    }

    /**
     * Setter for Size.
     * Size of the image
     * @param size Value for Size10
     */
    @JsonSetter("size")
    public void setSize(Size10 size) {
        this.size = size;
    }

    /**
     * Getter for VerificationCode.
     * (Deprecated)
     * @return Returns the String
     */
    @JsonGetter("verification_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVerificationCode() {
        return verificationCode;
    }

    /**
     * Setter for VerificationCode.
     * (Deprecated)
     * @param verificationCode Value for String
     */
    @JsonSetter("verification_code")
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this RedownloadImage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RedownloadImage [" + "authCookie=" + authCookie + ", showModal=" + showModal
                + ", size=" + size + ", verificationCode=" + verificationCode
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link RedownloadImage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RedownloadImage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .authCookie(getAuthCookie())
                .showModal(getShowModal())
                .size(getSize())
                .verificationCode(getVerificationCode());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link RedownloadImage}.
     */
    public static class Builder {
        private AuthCookie6 authCookie;
        private Boolean showModal;
        private Size10 size;
        private String verificationCode;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for authCookie.
         * @param  authCookie  AuthCookie6 value for authCookie.
         * @return Builder
         */
        public Builder authCookie(AuthCookie6 authCookie) {
            this.authCookie = authCookie;
            return this;
        }

        /**
         * Setter for showModal.
         * @param  showModal  Boolean value for showModal.
         * @return Builder
         */
        public Builder showModal(Boolean showModal) {
            this.showModal = showModal;
            return this;
        }

        /**
         * Setter for size.
         * @param  size  Size10 value for size.
         * @return Builder
         */
        public Builder size(Size10 size) {
            this.size = size;
            return this;
        }

        /**
         * Setter for verificationCode.
         * @param  verificationCode  String value for verificationCode.
         * @return Builder
         */
        public Builder verificationCode(String verificationCode) {
            this.verificationCode = verificationCode;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link RedownloadImage} object using the set fields.
         * @return {@link RedownloadImage}
         */
        public RedownloadImage build() {
            RedownloadImage model =
                    new RedownloadImage(authCookie, showModal, size, verificationCode);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
