/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Rights type.
 */
public class Rights {
    private String countries;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Rights() {
    }

    /**
     * Initialization constructor.
     * @param  countries  String value for countries.
     */
    public Rights(
            String countries) {
        this.countries = countries;
    }

    /**
     * Getter for Countries.
     * @return Returns the String
     */
    @JsonGetter("countries")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCountries() {
        return countries;
    }

    /**
     * Setter for Countries.
     * @param countries Value for String
     */
    @JsonSetter("countries")
    public void setCountries(String countries) {
        this.countries = countries;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Rights into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Rights [" + "countries=" + countries + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Rights.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Rights.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .countries(getCountries());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Rights}.
     */
    public static class Builder {
        private String countries;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for countries.
         * @param  countries  String value for countries.
         * @return Builder
         */
        public Builder countries(String countries) {
            this.countries = countries;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Rights} object using the set fields.
         * @return {@link Rights}
         */
        public Rights build() {
            Rights model =
                    new Rights(countries);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
