/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for SearchEntitiesResponse type.
 */
public class SearchEntitiesResponse {
    private List<String> keywords;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SearchEntitiesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  keywords  List of String value for keywords.
     */
    public SearchEntitiesResponse(
            List<String> keywords) {
        this.keywords = keywords;
    }

    /**
     * Getter for Keywords.
     * The top keywords from the submitted text
     * @return Returns the List of String
     */
    @JsonGetter("keywords")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getKeywords() {
        return keywords;
    }

    /**
     * Setter for Keywords.
     * The top keywords from the submitted text
     * @param keywords Value for List of String
     */
    @JsonSetter("keywords")
    public void setKeywords(List<String> keywords) {
        this.keywords = keywords;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SearchEntitiesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SearchEntitiesResponse [" + "keywords=" + keywords + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SearchEntitiesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SearchEntitiesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .keywords(getKeywords());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SearchEntitiesResponse}.
     */
    public static class Builder {
        private List<String> keywords;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for keywords.
         * @param  keywords  List of String value for keywords.
         * @return Builder
         */
        public Builder keywords(List<String> keywords) {
            this.keywords = keywords;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SearchEntitiesResponse} object using the set fields.
         * @return {@link SearchEntitiesResponse}
         */
        public SearchEntitiesResponse build() {
            SearchEntitiesResponse model =
                    new SearchEntitiesResponse(keywords);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
