/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Sfx type.
 */
public class Sfx {
    private LocalDate addedDate;
    private String affiliateUrl;
    private String artist;
    private SfxAssets assets;
    private Contributor contributor;
    private String description;
    private Double duration;
    private String id;
    private List<String> keywords;
    private String mediaType;
    private List<String> releases;
    private String title;
    private LocalDateTime updatedTime;
    private String url;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Sfx() {
    }

    /**
     * Initialization constructor.
     * @param  contributor  Contributor value for contributor.
     * @param  id  String value for id.
     * @param  mediaType  String value for mediaType.
     * @param  addedDate  LocalDate value for addedDate.
     * @param  affiliateUrl  String value for affiliateUrl.
     * @param  artist  String value for artist.
     * @param  assets  SfxAssets value for assets.
     * @param  description  String value for description.
     * @param  duration  Double value for duration.
     * @param  keywords  List of String value for keywords.
     * @param  releases  List of String value for releases.
     * @param  title  String value for title.
     * @param  updatedTime  LocalDateTime value for updatedTime.
     * @param  url  String value for url.
     */
    public Sfx(
            Contributor contributor,
            String id,
            String mediaType,
            LocalDate addedDate,
            String affiliateUrl,
            String artist,
            SfxAssets assets,
            String description,
            Double duration,
            List<String> keywords,
            List<String> releases,
            String title,
            LocalDateTime updatedTime,
            String url) {
        this.addedDate = addedDate;
        this.affiliateUrl = affiliateUrl;
        this.artist = artist;
        this.assets = assets;
        this.contributor = contributor;
        this.description = description;
        this.duration = duration;
        this.id = id;
        this.keywords = keywords;
        this.mediaType = mediaType;
        this.releases = releases;
        this.title = title;
        this.updatedTime = updatedTime;
        this.url = url;
    }

    /**
     * Getter for AddedDate.
     * Date this sound effect was added to the Shutterstock library
     * @return Returns the LocalDate
     */
    @JsonGetter("added_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getAddedDate() {
        return addedDate;
    }

    /**
     * Setter for AddedDate.
     * Date this sound effect was added to the Shutterstock library
     * @param addedDate Value for LocalDate
     */
    @JsonSetter("added_date")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setAddedDate(LocalDate addedDate) {
        this.addedDate = addedDate;
    }

    /**
     * Getter for AffiliateUrl.
     * Affiliate referral link; appears only for registered affiliate partners
     * @return Returns the String
     */
    @JsonGetter("affiliate_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAffiliateUrl() {
        return affiliateUrl;
    }

    /**
     * Setter for AffiliateUrl.
     * Affiliate referral link; appears only for registered affiliate partners
     * @param affiliateUrl Value for String
     */
    @JsonSetter("affiliate_url")
    public void setAffiliateUrl(String affiliateUrl) {
        this.affiliateUrl = affiliateUrl;
    }

    /**
     * Getter for Artist.
     * Artist of the sound effect
     * @return Returns the String
     */
    @JsonGetter("artist")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getArtist() {
        return artist;
    }

    /**
     * Setter for Artist.
     * Artist of the sound effect
     * @param artist Value for String
     */
    @JsonSetter("artist")
    public void setArtist(String artist) {
        this.artist = artist;
    }

    /**
     * Getter for Assets.
     * Files that are available as part of an sound effect asset
     * @return Returns the SfxAssets
     */
    @JsonGetter("assets")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SfxAssets getAssets() {
        return assets;
    }

    /**
     * Setter for Assets.
     * Files that are available as part of an sound effect asset
     * @param assets Value for SfxAssets
     */
    @JsonSetter("assets")
    public void setAssets(SfxAssets assets) {
        this.assets = assets;
    }

    /**
     * Getter for Contributor.
     * Information about a contributor
     * @return Returns the Contributor
     */
    @JsonGetter("contributor")
    public Contributor getContributor() {
        return contributor;
    }

    /**
     * Setter for Contributor.
     * Information about a contributor
     * @param contributor Value for Contributor
     */
    @JsonSetter("contributor")
    public void setContributor(Contributor contributor) {
        this.contributor = contributor;
    }

    /**
     * Getter for Description.
     * Description of this sound effect
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Description of this sound effect
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Duration.
     * Duration of this sound effect in seconds
     * @return Returns the Double
     */
    @JsonGetter("duration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getDuration() {
        return duration;
    }

    /**
     * Setter for Duration.
     * Duration of this sound effect in seconds
     * @param duration Value for Double
     */
    @JsonSetter("duration")
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /**
     * Getter for Id.
     * Shutterstock ID of this sound effect
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Shutterstock ID of this sound effect
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Keywords.
     * List of all keywords for this sound effect
     * @return Returns the List of String
     */
    @JsonGetter("keywords")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getKeywords() {
        return keywords;
    }

    /**
     * Setter for Keywords.
     * List of all keywords for this sound effect
     * @param keywords Value for List of String
     */
    @JsonSetter("keywords")
    public void setKeywords(List<String> keywords) {
        this.keywords = keywords;
    }

    /**
     * Getter for MediaType.
     * Media type of this track; should always be "sfx"
     * @return Returns the String
     */
    @JsonGetter("media_type")
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Setter for MediaType.
     * Media type of this track; should always be "sfx"
     * @param mediaType Value for String
     */
    @JsonSetter("media_type")
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * Getter for Releases.
     * List of all releases of this sound effect
     * @return Returns the List of String
     */
    @JsonGetter("releases")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getReleases() {
        return releases;
    }

    /**
     * Setter for Releases.
     * List of all releases of this sound effect
     * @param releases Value for List of String
     */
    @JsonSetter("releases")
    public void setReleases(List<String> releases) {
        this.releases = releases;
    }

    /**
     * Getter for Title.
     * Title of this sound effect
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * Title of this sound effect
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for UpdatedTime.
     * Time this sound effect was last updated
     * @return Returns the LocalDateTime
     */
    @JsonGetter("updated_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * Setter for UpdatedTime.
     * Time this sound effect was last updated
     * @param updatedTime Value for LocalDateTime
     */
    @JsonSetter("updated_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * Getter for Url.
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Sfx into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Sfx [" + "contributor=" + contributor + ", id=" + id + ", mediaType=" + mediaType
                + ", addedDate=" + addedDate + ", affiliateUrl=" + affiliateUrl + ", artist="
                + artist + ", assets=" + assets + ", description=" + description + ", duration="
                + duration + ", keywords=" + keywords + ", releases=" + releases + ", title="
                + title + ", updatedTime=" + updatedTime + ", url=" + url
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Sfx.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Sfx.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(contributor, id, mediaType)
                .addedDate(getAddedDate())
                .affiliateUrl(getAffiliateUrl())
                .artist(getArtist())
                .assets(getAssets())
                .description(getDescription())
                .duration(getDuration())
                .keywords(getKeywords())
                .releases(getReleases())
                .title(getTitle())
                .updatedTime(getUpdatedTime())
                .url(getUrl());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Sfx}.
     */
    public static class Builder {
        private Contributor contributor;
        private String id;
        private String mediaType;
        private LocalDate addedDate;
        private String affiliateUrl;
        private String artist;
        private SfxAssets assets;
        private String description;
        private Double duration;
        private List<String> keywords;
        private List<String> releases;
        private String title;
        private LocalDateTime updatedTime;
        private String url;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  contributor  Contributor value for contributor.
         * @param  id  String value for id.
         * @param  mediaType  String value for mediaType.
         */
        public Builder(Contributor contributor, String id, String mediaType) {
            this.contributor = contributor;
            this.id = id;
            this.mediaType = mediaType;
        }

        /**
         * Setter for contributor.
         * @param  contributor  Contributor value for contributor.
         * @return Builder
         */
        public Builder contributor(Contributor contributor) {
            this.contributor = contributor;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for mediaType.
         * @param  mediaType  String value for mediaType.
         * @return Builder
         */
        public Builder mediaType(String mediaType) {
            this.mediaType = mediaType;
            return this;
        }

        /**
         * Setter for addedDate.
         * @param  addedDate  LocalDate value for addedDate.
         * @return Builder
         */
        public Builder addedDate(LocalDate addedDate) {
            this.addedDate = addedDate;
            return this;
        }

        /**
         * Setter for affiliateUrl.
         * @param  affiliateUrl  String value for affiliateUrl.
         * @return Builder
         */
        public Builder affiliateUrl(String affiliateUrl) {
            this.affiliateUrl = affiliateUrl;
            return this;
        }

        /**
         * Setter for artist.
         * @param  artist  String value for artist.
         * @return Builder
         */
        public Builder artist(String artist) {
            this.artist = artist;
            return this;
        }

        /**
         * Setter for assets.
         * @param  assets  SfxAssets value for assets.
         * @return Builder
         */
        public Builder assets(SfxAssets assets) {
            this.assets = assets;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for duration.
         * @param  duration  Double value for duration.
         * @return Builder
         */
        public Builder duration(Double duration) {
            this.duration = duration;
            return this;
        }

        /**
         * Setter for keywords.
         * @param  keywords  List of String value for keywords.
         * @return Builder
         */
        public Builder keywords(List<String> keywords) {
            this.keywords = keywords;
            return this;
        }

        /**
         * Setter for releases.
         * @param  releases  List of String value for releases.
         * @return Builder
         */
        public Builder releases(List<String> releases) {
            this.releases = releases;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for updatedTime.
         * @param  updatedTime  LocalDateTime value for updatedTime.
         * @return Builder
         */
        public Builder updatedTime(LocalDateTime updatedTime) {
            this.updatedTime = updatedTime;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Sfx} object using the set fields.
         * @return {@link Sfx}
         */
        public Sfx build() {
            Sfx model =
                    new Sfx(contributor, id, mediaType, addedDate, affiliateUrl, artist, assets,
                            description, duration, keywords, releases, title, updatedTime, url);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
