/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Sort24 to be used.
 */
public enum Sort24 {
    NEWEST,

    LAST_UPDATED,

    ITEM_COUNT;

    private static TreeMap<String, Sort24> valueMap = new TreeMap<>();
    private String value;

    static {
        NEWEST.value = "newest";
        LAST_UPDATED.value = "last_updated";
        ITEM_COUNT.value = "item_count";

        valueMap.put("newest", NEWEST);
        valueMap.put("last_updated", LAST_UPDATED);
        valueMap.put("item_count", ITEM_COUNT);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Sort24 constructFromString(String toConvert) throws IOException {
        Sort24 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Sort24 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Sort24 values to list of string values.
     * @param toConvert The list of Sort24 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Sort24> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Sort24 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 