/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Subscription type.
 */
public class Subscription {
    private Allotment allotment;
    private String description;
    private LocalDateTime expirationTime;
    private List<LicenseFormat> formats;
    private String id;
    private String license;
    private String assetType;
    private Object metadata;
    private Price pricePerDownload;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Subscription() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  allotment  Allotment value for allotment.
     * @param  description  String value for description.
     * @param  expirationTime  LocalDateTime value for expirationTime.
     * @param  formats  List of LicenseFormat value for formats.
     * @param  license  String value for license.
     * @param  assetType  String value for assetType.
     * @param  metadata  Object value for metadata.
     * @param  pricePerDownload  Price value for pricePerDownload.
     */
    public Subscription(
            String id,
            Allotment allotment,
            String description,
            LocalDateTime expirationTime,
            List<LicenseFormat> formats,
            String license,
            String assetType,
            Object metadata,
            Price pricePerDownload) {
        this.allotment = allotment;
        this.description = description;
        this.expirationTime = expirationTime;
        this.formats = formats;
        this.id = id;
        this.license = license;
        this.assetType = assetType;
        this.metadata = metadata;
        this.pricePerDownload = pricePerDownload;
    }

    /**
     * Getter for Allotment.
     * An allotment of credits as part of a subscription
     * @return Returns the Allotment
     */
    @JsonGetter("allotment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Allotment getAllotment() {
        return allotment;
    }

    /**
     * Setter for Allotment.
     * An allotment of credits as part of a subscription
     * @param allotment Value for Allotment
     */
    @JsonSetter("allotment")
    public void setAllotment(Allotment allotment) {
        this.allotment = allotment;
    }

    /**
     * Getter for Description.
     * Description of the subscription
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Description of the subscription
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for ExpirationTime.
     * Date the subscription ends
     * @return Returns the LocalDateTime
     */
    @JsonGetter("expiration_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getExpirationTime() {
        return expirationTime;
    }

    /**
     * Setter for ExpirationTime.
     * Date the subscription ends
     * @param expirationTime Value for LocalDateTime
     */
    @JsonSetter("expiration_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setExpirationTime(LocalDateTime expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * Getter for Formats.
     * List of formats that are licensable for the subscription
     * @return Returns the List of LicenseFormat
     */
    @JsonGetter("formats")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<LicenseFormat> getFormats() {
        return formats;
    }

    /**
     * Setter for Formats.
     * List of formats that are licensable for the subscription
     * @param formats Value for List of LicenseFormat
     */
    @JsonSetter("formats")
    public void setFormats(List<LicenseFormat> formats) {
        this.formats = formats;
    }

    /**
     * Getter for Id.
     * Unique internal identifier for the subscription
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique internal identifier for the subscription
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for License.
     * Internal identifier for the type of subscription
     * @return Returns the String
     */
    @JsonGetter("license")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLicense() {
        return license;
    }

    /**
     * Setter for License.
     * Internal identifier for the type of subscription
     * @param license Value for String
     */
    @JsonSetter("license")
    public void setLicense(String license) {
        this.license = license;
    }

    /**
     * Getter for AssetType.
     * Identifier for the type of assets associated with this subscription (images, videos, audio,
     * editorial)
     * @return Returns the String
     */
    @JsonGetter("asset_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAssetType() {
        return assetType;
    }

    /**
     * Setter for AssetType.
     * Identifier for the type of assets associated with this subscription (images, videos, audio,
     * editorial)
     * @param assetType Value for String
     */
    @JsonSetter("asset_type")
    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }

    /**
     * Getter for Metadata.
     * Subscription metadata; different for each customer
     * @return Returns the Object
     */
    @JsonGetter("metadata")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getMetadata() {
        return metadata;
    }

    /**
     * Setter for Metadata.
     * Subscription metadata; different for each customer
     * @param metadata Value for Object
     */
    @JsonSetter("metadata")
    public void setMetadata(Object metadata) {
        this.metadata = metadata;
    }

    /**
     * Getter for PricePerDownload.
     * Price
     * @return Returns the Price
     */
    @JsonGetter("price_per_download")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Price getPricePerDownload() {
        return pricePerDownload;
    }

    /**
     * Setter for PricePerDownload.
     * Price
     * @param pricePerDownload Value for Price
     */
    @JsonSetter("price_per_download")
    public void setPricePerDownload(Price pricePerDownload) {
        this.pricePerDownload = pricePerDownload;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Subscription into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Subscription [" + "id=" + id + ", allotment=" + allotment + ", description="
                + description + ", expirationTime=" + expirationTime + ", formats=" + formats
                + ", license=" + license + ", assetType=" + assetType + ", metadata=" + metadata
                + ", pricePerDownload=" + pricePerDownload + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Subscription.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Subscription.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id)
                .allotment(getAllotment())
                .description(getDescription())
                .expirationTime(getExpirationTime())
                .formats(getFormats())
                .license(getLicense())
                .assetType(getAssetType())
                .metadata(getMetadata())
                .pricePerDownload(getPricePerDownload());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Subscription}.
     */
    public static class Builder {
        private String id;
        private Allotment allotment;
        private String description;
        private LocalDateTime expirationTime;
        private List<LicenseFormat> formats;
        private String license;
        private String assetType;
        private Object metadata;
        private Price pricePerDownload;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         */
        public Builder(String id) {
            this.id = id;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for allotment.
         * @param  allotment  Allotment value for allotment.
         * @return Builder
         */
        public Builder allotment(Allotment allotment) {
            this.allotment = allotment;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for expirationTime.
         * @param  expirationTime  LocalDateTime value for expirationTime.
         * @return Builder
         */
        public Builder expirationTime(LocalDateTime expirationTime) {
            this.expirationTime = expirationTime;
            return this;
        }

        /**
         * Setter for formats.
         * @param  formats  List of LicenseFormat value for formats.
         * @return Builder
         */
        public Builder formats(List<LicenseFormat> formats) {
            this.formats = formats;
            return this;
        }

        /**
         * Setter for license.
         * @param  license  String value for license.
         * @return Builder
         */
        public Builder license(String license) {
            this.license = license;
            return this;
        }

        /**
         * Setter for assetType.
         * @param  assetType  String value for assetType.
         * @return Builder
         */
        public Builder assetType(String assetType) {
            this.assetType = assetType;
            return this;
        }

        /**
         * Setter for metadata.
         * @param  metadata  Object value for metadata.
         * @return Builder
         */
        public Builder metadata(Object metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Setter for pricePerDownload.
         * @param  pricePerDownload  Price value for pricePerDownload.
         * @return Builder
         */
        public Builder pricePerDownload(Price pricePerDownload) {
            this.pricePerDownload = pricePerDownload;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Subscription} object using the set fields.
         * @return {@link Subscription}
         */
        public Subscription build() {
            Subscription model =
                    new Subscription(id, allotment, description, expirationTime, formats, license,
                            assetType, metadata, pricePerDownload);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
