/*
 * Shutterstock
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shutterstock.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for UpdatedMedia type.
 */
public class UpdatedMedia {
    private String id;
    private LocalDateTime updatedTime;
    private List<String> updates;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UpdatedMedia() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  updatedTime  LocalDateTime value for updatedTime.
     * @param  updates  List of String value for updates.
     */
    public UpdatedMedia(
            String id,
            LocalDateTime updatedTime,
            List<String> updates) {
        this.id = id;
        this.updatedTime = updatedTime;
        this.updates = updates;
    }

    /**
     * Getter for Id.
     * ID of the media
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * ID of the media
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for UpdatedTime.
     * Date that the media was updated
     * @return Returns the LocalDateTime
     */
    @JsonGetter("updated_time")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * Setter for UpdatedTime.
     * Date that the media was updated
     * @param updatedTime Value for LocalDateTime
     */
    @JsonSetter("updated_time")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * Getter for Updates.
     * Types of updates that were made to the piece of media
     * @return Returns the List of String
     */
    @JsonGetter("updates")
    public List<String> getUpdates() {
        return updates;
    }

    /**
     * Setter for Updates.
     * Types of updates that were made to the piece of media
     * @param updates Value for List of String
     */
    @JsonSetter("updates")
    public void setUpdates(List<String> updates) {
        this.updates = updates;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UpdatedMedia into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdatedMedia [" + "id=" + id + ", updatedTime=" + updatedTime + ", updates="
                + updates + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link UpdatedMedia.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdatedMedia.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, updatedTime, updates);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UpdatedMedia}.
     */
    public static class Builder {
        private String id;
        private LocalDateTime updatedTime;
        private List<String> updates;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  updatedTime  LocalDateTime value for updatedTime.
         * @param  updates  List of String value for updates.
         */
        public Builder(String id, LocalDateTime updatedTime, List<String> updates) {
            this.id = id;
            this.updatedTime = updatedTime;
            this.updates = updates;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for updatedTime.
         * @param  updatedTime  LocalDateTime value for updatedTime.
         * @return Builder
         */
        public Builder updatedTime(LocalDateTime updatedTime) {
            this.updatedTime = updatedTime;
            return this;
        }

        /**
         * Setter for updates.
         * @param  updates  List of String value for updates.
         * @return Builder
         */
        public Builder updates(List<String> updates) {
            this.updates = updates;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UpdatedMedia} object using the set fields.
         * @return {@link UpdatedMedia}
         */
        public UpdatedMedia build() {
            UpdatedMedia model =
                    new UpdatedMedia(id, updatedTime, updates);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
