/*
 * ShutterstockApiExplorerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shutterstock.api.apis;

import com.shutterstock.api.ApiHelper;
import com.shutterstock.api.DateTimeHelper;
import com.shutterstock.api.Server;
import com.shutterstock.api.exceptions.ApiException;
import com.shutterstock.api.http.request.HttpMethod;
import com.shutterstock.api.http.response.ApiResponse;
import com.shutterstock.api.models.AspectRatio;
import com.shutterstock.api.models.CategoryDataList;
import com.shutterstock.api.models.CollectionCreateRequest;
import com.shutterstock.api.models.CollectionCreateResponse;
import com.shutterstock.api.models.CollectionDataList;
import com.shutterstock.api.models.CollectionItemDataList;
import com.shutterstock.api.models.CollectionItemRequest;
import com.shutterstock.api.models.CollectionUpdateRequest;
import com.shutterstock.api.models.DownloadAvailability;
import com.shutterstock.api.models.DownloadHistoryDataList;
import com.shutterstock.api.models.Embed;
import com.shutterstock.api.models.Language;
import com.shutterstock.api.models.License9;
import com.shutterstock.api.models.LicenseVideoRequest;
import com.shutterstock.api.models.LicenseVideoResultDataList;
import com.shutterstock.api.models.MCollection;
import com.shutterstock.api.models.Orientation2;
import com.shutterstock.api.models.PeopleAge2;
import com.shutterstock.api.models.PeopleEthnicity5;
import com.shutterstock.api.models.PeopleGender2;
import com.shutterstock.api.models.RedownloadVideo;
import com.shutterstock.api.models.Resolution;
import com.shutterstock.api.models.Size16;
import com.shutterstock.api.models.Sort2;
import com.shutterstock.api.models.Sort5;
import com.shutterstock.api.models.Suggestions;
import com.shutterstock.api.models.UpdatedMediaDataList;
import com.shutterstock.api.models.Url;
import com.shutterstock.api.models.Video;
import com.shutterstock.api.models.VideoDataList;
import com.shutterstock.api.models.VideoSearchResults;
import com.shutterstock.api.models.View2;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class VideosApi extends BaseApi {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public VideosApi(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * This endpoint searches for videos. If you specify more than one search parameter, the API
     * uses an AND condition. Array parameters can be specified multiple times; in this case, the
     * API uses an AND or an OR condition with those values, depending on the parameter. You can
     * also filter search terms out in the `query` parameter by prefixing the term with NOT.
     * @param  addedDate  Optional parameter: Show videos added on the specified date
     * @param  addedDateStart  Optional parameter: Show videos added on or after the specified date
     * @param  addedDateEnd  Optional parameter: Show videos added before the specified date
     * @param  aspectRatio  Optional parameter: Show videos with the specified aspect ratio
     * @param  category  Optional parameter: Show videos with the specified Shutterstock-defined
     *         category; specify a category name or ID
     * @param  contributor  Optional parameter: Show videos with the specified artist names or IDs
     * @param  contributorCountry  Optional parameter: Show videos from contributors in one or more
     *         specified countries
     * @param  duration  Optional parameter: (Deprecated; use duration_from and duration_to instead)
     *         Show videos with the specified duration in seconds
     * @param  durationFrom  Optional parameter: Show videos with the specified duration or longer
     *         in seconds
     * @param  durationTo  Optional parameter: Show videos with the specified duration or shorter in
     *         seconds
     * @param  fps  Optional parameter: (Deprecated; use fps_from and fps_to instead) Show videos
     *         with the specified frames per second
     * @param  fpsFrom  Optional parameter: Show videos with the specified frames per second or more
     * @param  fpsTo  Optional parameter: Show videos with the specified frames per second or fewer
     * @param  keywordSafeSearch  Optional parameter: Hide results with potentially unsafe keywords
     * @param  language  Optional parameter: Set query and result language (uses Accept-Language
     *         header if not set)
     * @param  license  Optional parameter: Show only videos with the specified license or licenses
     * @param  model  Optional parameter: Show videos with each of the specified models
     * @param  orientation  Optional parameter: Search for videos in a specific orientation
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  peopleAge  Optional parameter: Show videos that feature people of the specified age
     *         range
     * @param  peopleEthnicity  Optional parameter: Show videos with people of the specified
     *         ethnicities
     * @param  peopleGender  Optional parameter: Show videos with people with the specified gender
     * @param  peopleNumber  Optional parameter: Show videos with the specified number of people
     * @param  peopleModelReleased  Optional parameter: Show only videos of people with a signed
     *         model release
     * @param  query  Optional parameter: One or more search terms separated by spaces; you can use
     *         NOT to filter out videos that match a term
     * @param  resolution  Optional parameter: Show videos with the specified resolution
     * @param  safe  Optional parameter: Enable or disable safe search
     * @param  sort  Optional parameter: Sort by one of these categories
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @return    Returns the VideoSearchResults wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<VideoSearchResults> searchVideos(
            final LocalDate addedDate,
            final LocalDate addedDateStart,
            final LocalDate addedDateEnd,
            final AspectRatio aspectRatio,
            final String category,
            final List<String> contributor,
            final List<String> contributorCountry,
            final Integer duration,
            final Integer durationFrom,
            final Integer durationTo,
            final Double fps,
            final Double fpsFrom,
            final Double fpsTo,
            final Boolean keywordSafeSearch,
            final Language language,
            final List<License9> license,
            final List<String> model,
            final Orientation2 orientation,
            final Integer page,
            final Integer perPage,
            final PeopleAge2 peopleAge,
            final List<PeopleEthnicity5> peopleEthnicity,
            final PeopleGender2 peopleGender,
            final Integer peopleNumber,
            final Boolean peopleModelReleased,
            final String query,
            final Resolution resolution,
            final Boolean safe,
            final Sort2 sort,
            final View2 view) throws ApiException, IOException {
        return prepareSearchVideosRequest(addedDate, addedDateStart, addedDateEnd, aspectRatio,
                category, contributor, contributorCountry, duration, durationFrom, durationTo, fps,
                fpsFrom, fpsTo, keywordSafeSearch, language, license, model, orientation, page,
                perPage, peopleAge, peopleEthnicity, peopleGender, peopleNumber,
                peopleModelReleased, query, resolution, safe, sort, view).execute();
    }

    /**
     * This endpoint searches for videos. If you specify more than one search parameter, the API
     * uses an AND condition. Array parameters can be specified multiple times; in this case, the
     * API uses an AND or an OR condition with those values, depending on the parameter. You can
     * also filter search terms out in the `query` parameter by prefixing the term with NOT.
     * @param  addedDate  Optional parameter: Show videos added on the specified date
     * @param  addedDateStart  Optional parameter: Show videos added on or after the specified date
     * @param  addedDateEnd  Optional parameter: Show videos added before the specified date
     * @param  aspectRatio  Optional parameter: Show videos with the specified aspect ratio
     * @param  category  Optional parameter: Show videos with the specified Shutterstock-defined
     *         category; specify a category name or ID
     * @param  contributor  Optional parameter: Show videos with the specified artist names or IDs
     * @param  contributorCountry  Optional parameter: Show videos from contributors in one or more
     *         specified countries
     * @param  duration  Optional parameter: (Deprecated; use duration_from and duration_to instead)
     *         Show videos with the specified duration in seconds
     * @param  durationFrom  Optional parameter: Show videos with the specified duration or longer
     *         in seconds
     * @param  durationTo  Optional parameter: Show videos with the specified duration or shorter in
     *         seconds
     * @param  fps  Optional parameter: (Deprecated; use fps_from and fps_to instead) Show videos
     *         with the specified frames per second
     * @param  fpsFrom  Optional parameter: Show videos with the specified frames per second or more
     * @param  fpsTo  Optional parameter: Show videos with the specified frames per second or fewer
     * @param  keywordSafeSearch  Optional parameter: Hide results with potentially unsafe keywords
     * @param  language  Optional parameter: Set query and result language (uses Accept-Language
     *         header if not set)
     * @param  license  Optional parameter: Show only videos with the specified license or licenses
     * @param  model  Optional parameter: Show videos with each of the specified models
     * @param  orientation  Optional parameter: Search for videos in a specific orientation
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  peopleAge  Optional parameter: Show videos that feature people of the specified age
     *         range
     * @param  peopleEthnicity  Optional parameter: Show videos with people of the specified
     *         ethnicities
     * @param  peopleGender  Optional parameter: Show videos with people with the specified gender
     * @param  peopleNumber  Optional parameter: Show videos with the specified number of people
     * @param  peopleModelReleased  Optional parameter: Show only videos of people with a signed
     *         model release
     * @param  query  Optional parameter: One or more search terms separated by spaces; you can use
     *         NOT to filter out videos that match a term
     * @param  resolution  Optional parameter: Show videos with the specified resolution
     * @param  safe  Optional parameter: Enable or disable safe search
     * @param  sort  Optional parameter: Sort by one of these categories
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @return    Returns the VideoSearchResults wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<VideoSearchResults>> searchVideosAsync(
            final LocalDate addedDate,
            final LocalDate addedDateStart,
            final LocalDate addedDateEnd,
            final AspectRatio aspectRatio,
            final String category,
            final List<String> contributor,
            final List<String> contributorCountry,
            final Integer duration,
            final Integer durationFrom,
            final Integer durationTo,
            final Double fps,
            final Double fpsFrom,
            final Double fpsTo,
            final Boolean keywordSafeSearch,
            final Language language,
            final List<License9> license,
            final List<String> model,
            final Orientation2 orientation,
            final Integer page,
            final Integer perPage,
            final PeopleAge2 peopleAge,
            final List<PeopleEthnicity5> peopleEthnicity,
            final PeopleGender2 peopleGender,
            final Integer peopleNumber,
            final Boolean peopleModelReleased,
            final String query,
            final Resolution resolution,
            final Boolean safe,
            final Sort2 sort,
            final View2 view) {
        try {
            return prepareSearchVideosRequest(addedDate, addedDateStart, addedDateEnd, aspectRatio,
            category, contributor, contributorCountry, duration, durationFrom, durationTo, fps,
            fpsFrom, fpsTo, keywordSafeSearch, language, license, model, orientation, page, perPage,
            peopleAge, peopleEthnicity, peopleGender, peopleNumber, peopleModelReleased, query,
            resolution, safe, sort, view).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for searchVideos.
     */
    private ApiCall<ApiResponse<VideoSearchResults>, ApiException> prepareSearchVideosRequest(
            final LocalDate addedDate,
            final LocalDate addedDateStart,
            final LocalDate addedDateEnd,
            final AspectRatio aspectRatio,
            final String category,
            final List<String> contributor,
            final List<String> contributorCountry,
            final Integer duration,
            final Integer durationFrom,
            final Integer durationTo,
            final Double fps,
            final Double fpsFrom,
            final Double fpsTo,
            final Boolean keywordSafeSearch,
            final Language language,
            final List<License9> license,
            final List<String> model,
            final Orientation2 orientation,
            final Integer page,
            final Integer perPage,
            final PeopleAge2 peopleAge,
            final List<PeopleEthnicity5> peopleEthnicity,
            final PeopleGender2 peopleGender,
            final Integer peopleNumber,
            final Boolean peopleModelReleased,
            final String query,
            final Resolution resolution,
            final Boolean safe,
            final Sort2 sort,
            final View2 view) {
        return new ApiCall.Builder<ApiResponse<VideoSearchResults>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/search")
                        .queryParam(param -> param.key("added_date")
                                .value(DateTimeHelper.toSimpleDate(addedDate)).isRequired(false))
                        .queryParam(param -> param.key("added_date_start")
                                .value(DateTimeHelper.toSimpleDate(addedDateStart)).isRequired(false))
                        .queryParam(param -> param.key("added_date_end")
                                .value(DateTimeHelper.toSimpleDate(addedDateEnd)).isRequired(false))
                        .queryParam(param -> param.key("aspect_ratio")
                                .value((aspectRatio != null) ? aspectRatio.value() : null).isRequired(false))
                        .queryParam(param -> param.key("category")
                                .value(category).isRequired(false))
                        .queryParam(param -> param.key("contributor")
                                .value(contributor).isRequired(false))
                        .queryParam(param -> param.key("contributor_country")
                                .value(contributorCountry).isRequired(false))
                        .queryParam(param -> param.key("duration")
                                .value(duration).isRequired(false))
                        .queryParam(param -> param.key("duration_from")
                                .value(durationFrom).isRequired(false))
                        .queryParam(param -> param.key("duration_to")
                                .value(durationTo).isRequired(false))
                        .queryParam(param -> param.key("fps")
                                .value(fps).isRequired(false))
                        .queryParam(param -> param.key("fps_from")
                                .value(fpsFrom).isRequired(false))
                        .queryParam(param -> param.key("fps_to")
                                .value(fpsTo).isRequired(false))
                        .queryParam(param -> param.key("keyword_safe_search")
                                .value((keywordSafeSearch != null) ? keywordSafeSearch : true).isRequired(false))
                        .queryParam(param -> param.key("language")
                                .value((language != null) ? language.value() : null).isRequired(false))
                        .queryParam(param -> param.key("license")
                                .value(License9.toValue(license)).isRequired(false))
                        .queryParam(param -> param.key("model")
                                .value(model).isRequired(false))
                        .queryParam(param -> param.key("orientation")
                                .value((orientation != null) ? orientation.value() : null).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("per_page")
                                .value((perPage != null) ? perPage : 20).isRequired(false))
                        .queryParam(param -> param.key("people_age")
                                .value((peopleAge != null) ? peopleAge.value() : null).isRequired(false))
                        .queryParam(param -> param.key("people_ethnicity")
                                .value(PeopleEthnicity5.toValue(peopleEthnicity)).isRequired(false))
                        .queryParam(param -> param.key("people_gender")
                                .value((peopleGender != null) ? peopleGender.value() : null).isRequired(false))
                        .queryParam(param -> param.key("people_number")
                                .value(peopleNumber).isRequired(false))
                        .queryParam(param -> param.key("people_model_released")
                                .value(peopleModelReleased).isRequired(false))
                        .queryParam(param -> param.key("query")
                                .value(query).isRequired(false))
                        .queryParam(param -> param.key("resolution")
                                .value((resolution != null) ? resolution.value() : null).isRequired(false))
                        .queryParam(param -> param.key("safe")
                                .value((safe != null) ? safe : true).isRequired(false))
                        .queryParam(param -> param.key("sort")
                                .value((sort != null) ? sort.value() : "popular").isRequired(false))
                        .queryParam(param -> param.key("view")
                                .value((view != null) ? view.value() : "minimal").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("basic")
                                        .add("customer_accessCode")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, VideoSearchResults.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint provides autocomplete suggestions for partial search terms.
     * @param  query  Required parameter: Search term for which you want keyword suggestions
     * @param  limit  Optional parameter: Limit the number of the suggestions
     * @return    Returns the Suggestions wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<Suggestions> getVideoSuggestions(
            final String query,
            final Integer limit) throws ApiException, IOException {
        return prepareGetVideoSuggestionsRequest(query, limit).execute();
    }

    /**
     * This endpoint provides autocomplete suggestions for partial search terms.
     * @param  query  Required parameter: Search term for which you want keyword suggestions
     * @param  limit  Optional parameter: Limit the number of the suggestions
     * @return    Returns the Suggestions wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<Suggestions>> getVideoSuggestionsAsync(
            final String query,
            final Integer limit) {
        try {
            return prepareGetVideoSuggestionsRequest(query, limit).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getVideoSuggestions.
     */
    private ApiCall<ApiResponse<Suggestions>, ApiException> prepareGetVideoSuggestionsRequest(
            final String query,
            final Integer limit) {
        return new ApiCall.Builder<ApiResponse<Suggestions>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/search/suggestions")
                        .queryParam(param -> param.key("query")
                                .value(query))
                        .queryParam(param -> param.key("limit")
                                .value((limit != null) ? limit : 10).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("basic")
                                        .add("customer_accessCode")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, Suggestions.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint lists information about one or more videos, including the aspect ratio and URLs
     * to previews.
     * @param  id  Required parameter: One or more video IDs
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @param  searchId  Optional parameter: The ID of the search that is related to this request
     * @return    Returns the VideoDataList wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<VideoDataList> getVideoList(
            final List<String> id,
            final View2 view,
            final String searchId) throws ApiException, IOException {
        return prepareGetVideoListRequest(id, view, searchId).execute();
    }

    /**
     * This endpoint lists information about one or more videos, including the aspect ratio and URLs
     * to previews.
     * @param  id  Required parameter: One or more video IDs
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @param  searchId  Optional parameter: The ID of the search that is related to this request
     * @return    Returns the VideoDataList wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<VideoDataList>> getVideoListAsync(
            final List<String> id,
            final View2 view,
            final String searchId) {
        try {
            return prepareGetVideoListRequest(id, view, searchId).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getVideoList.
     */
    private ApiCall<ApiResponse<VideoDataList>, ApiException> prepareGetVideoListRequest(
            final List<String> id,
            final View2 view,
            final String searchId) {
        return new ApiCall.Builder<ApiResponse<VideoDataList>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos")
                        .queryParam(param -> param.key("id")
                                .value(id))
                        .queryParam(param -> param.key("view")
                                .value((view != null) ? view.value() : "minimal").isRequired(false))
                        .queryParam(param -> param.key("search_id")
                                .value(searchId).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("basic")
                                        .add("customer_accessCode")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, VideoDataList.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint shows information about a video, including URLs to previews and the sizes that
     * it is available in.
     * @param  id  Required parameter: Video ID
     * @param  language  Optional parameter: Language for the keywords and categories in the
     *         response
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @param  searchId  Optional parameter: The ID of the search that is related to this request
     * @return    Returns the Video wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<Video> getVideo(
            final String id,
            final Language language,
            final View2 view,
            final String searchId) throws ApiException, IOException {
        return prepareGetVideoRequest(id, language, view, searchId).execute();
    }

    /**
     * This endpoint shows information about a video, including URLs to previews and the sizes that
     * it is available in.
     * @param  id  Required parameter: Video ID
     * @param  language  Optional parameter: Language for the keywords and categories in the
     *         response
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @param  searchId  Optional parameter: The ID of the search that is related to this request
     * @return    Returns the Video wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<Video>> getVideoAsync(
            final String id,
            final Language language,
            final View2 view,
            final String searchId) {
        try {
            return prepareGetVideoRequest(id, language, view, searchId).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getVideo.
     */
    private ApiCall<ApiResponse<Video>, ApiException> prepareGetVideoRequest(
            final String id,
            final Language language,
            final View2 view,
            final String searchId) {
        return new ApiCall.Builder<ApiResponse<Video>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/{id}")
                        .queryParam(param -> param.key("language")
                                .value((language != null) ? language.value() : null).isRequired(false))
                        .queryParam(param -> param.key("view")
                                .value((view != null) ? view.value() : "full").isRequired(false))
                        .queryParam(param -> param.key("search_id")
                                .value(searchId).isRequired(false))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("basic")
                                        .add("customer_accessCode")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, Video.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint gets licenses for one or more videos. You must specify the video IDs in the
     * body parameter and the size and subscription ID either in the query parameter or with each
     * video ID in the body parameter. Values in the body parameter override values in the query
     * parameters. The download links in the response are valid for 8 hours.
     * @param  body  Required parameter: List of videos to request licenses for and information
     *         about each license transaction; these values override the defaults in the query
     *         parameters
     * @param  subscriptionId  Optional parameter: The subscription ID to use for licensing
     * @param  size  Optional parameter: The size of the video to license
     * @param  searchId  Optional parameter: The Search ID that led to this licensing event
     * @return    Returns the LicenseVideoResultDataList wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<LicenseVideoResultDataList> licenseVideos(
            final LicenseVideoRequest body,
            final String subscriptionId,
            final Size16 size,
            final String searchId) throws ApiException, IOException {
        return prepareLicenseVideosRequest(body, subscriptionId, size, searchId).execute();
    }

    /**
     * This endpoint gets licenses for one or more videos. You must specify the video IDs in the
     * body parameter and the size and subscription ID either in the query parameter or with each
     * video ID in the body parameter. Values in the body parameter override values in the query
     * parameters. The download links in the response are valid for 8 hours.
     * @param  body  Required parameter: List of videos to request licenses for and information
     *         about each license transaction; these values override the defaults in the query
     *         parameters
     * @param  subscriptionId  Optional parameter: The subscription ID to use for licensing
     * @param  size  Optional parameter: The size of the video to license
     * @param  searchId  Optional parameter: The Search ID that led to this licensing event
     * @return    Returns the LicenseVideoResultDataList wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<LicenseVideoResultDataList>> licenseVideosAsync(
            final LicenseVideoRequest body,
            final String subscriptionId,
            final Size16 size,
            final String searchId) {
        try {
            return prepareLicenseVideosRequest(body, subscriptionId, size, searchId).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for licenseVideos.
     */
    private ApiCall<ApiResponse<LicenseVideoResultDataList>, ApiException> prepareLicenseVideosRequest(
            final LicenseVideoRequest body,
            final String subscriptionId,
            final Size16 size,
            final String searchId) {
        return new ApiCall.Builder<ApiResponse<LicenseVideoResultDataList>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/licenses")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .queryParam(param -> param.key("subscription_id")
                                .value(subscriptionId).isRequired(false))
                        .queryParam(param -> param.key("size")
                                .value((size != null) ? size.value() : "web").isRequired(false))
                        .queryParam(param -> param.key("search_id")
                                .value(searchId).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, LicenseVideoResultDataList.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint lists existing licenses.
     * @param  videoId  Optional parameter: Show licenses for the specified video ID
     * @param  license  Optional parameter: Show videos that are available with the specified
     *         license, such as `standard` or `enhanced`
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  sort  Optional parameter: Sort by oldest or newest videos first
     * @param  username  Optional parameter: Filter licenses by username of licensee
     * @param  startDate  Optional parameter: Show licenses created on or after the specified date
     * @param  endDate  Optional parameter: Show licenses created before the specified date
     * @param  downloadAvailability  Optional parameter: Filter licenses by download availability
     * @param  teamHistory  Optional parameter: Set to true to see license history for all members
     *         of your team.
     * @return    Returns the DownloadHistoryDataList wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<DownloadHistoryDataList> getVideoLicenseList(
            final String videoId,
            final String license,
            final Integer page,
            final Integer perPage,
            final Sort5 sort,
            final String username,
            final LocalDateTime startDate,
            final LocalDateTime endDate,
            final DownloadAvailability downloadAvailability,
            final Boolean teamHistory) throws ApiException, IOException {
        return prepareGetVideoLicenseListRequest(videoId, license, page, perPage, sort, username,
                startDate, endDate, downloadAvailability, teamHistory).execute();
    }

    /**
     * This endpoint lists existing licenses.
     * @param  videoId  Optional parameter: Show licenses for the specified video ID
     * @param  license  Optional parameter: Show videos that are available with the specified
     *         license, such as `standard` or `enhanced`
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  sort  Optional parameter: Sort by oldest or newest videos first
     * @param  username  Optional parameter: Filter licenses by username of licensee
     * @param  startDate  Optional parameter: Show licenses created on or after the specified date
     * @param  endDate  Optional parameter: Show licenses created before the specified date
     * @param  downloadAvailability  Optional parameter: Filter licenses by download availability
     * @param  teamHistory  Optional parameter: Set to true to see license history for all members
     *         of your team.
     * @return    Returns the DownloadHistoryDataList wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<DownloadHistoryDataList>> getVideoLicenseListAsync(
            final String videoId,
            final String license,
            final Integer page,
            final Integer perPage,
            final Sort5 sort,
            final String username,
            final LocalDateTime startDate,
            final LocalDateTime endDate,
            final DownloadAvailability downloadAvailability,
            final Boolean teamHistory) {
        try {
            return prepareGetVideoLicenseListRequest(videoId, license, page, perPage, sort, username,
            startDate, endDate, downloadAvailability, teamHistory).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getVideoLicenseList.
     */
    private ApiCall<ApiResponse<DownloadHistoryDataList>, ApiException> prepareGetVideoLicenseListRequest(
            final String videoId,
            final String license,
            final Integer page,
            final Integer perPage,
            final Sort5 sort,
            final String username,
            final LocalDateTime startDate,
            final LocalDateTime endDate,
            final DownloadAvailability downloadAvailability,
            final Boolean teamHistory) {
        return new ApiCall.Builder<ApiResponse<DownloadHistoryDataList>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/licenses")
                        .queryParam(param -> param.key("video_id")
                                .value(videoId).isRequired(false))
                        .queryParam(param -> param.key("license")
                                .value(license).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("per_page")
                                .value((perPage != null) ? perPage : 20).isRequired(false))
                        .queryParam(param -> param.key("sort")
                                .value((sort != null) ? sort.value() : "newest").isRequired(false))
                        .queryParam(param -> param.key("username")
                                .value(username).isRequired(false))
                        .queryParam(param -> param.key("start_date")
                                .value(DateTimeHelper.toRfc8601DateTime(startDate)).isRequired(false))
                        .queryParam(param -> param.key("end_date")
                                .value(DateTimeHelper.toRfc8601DateTime(endDate)).isRequired(false))
                        .queryParam(param -> param.key("download_availability")
                                .value((downloadAvailability != null) ? downloadAvailability.value() : "all").isRequired(false))
                        .queryParam(param -> param.key("team_history")
                                .value((teamHistory != null) ? teamHistory : false).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, DownloadHistoryDataList.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint redownloads videos that you have already received a license for.
     * @param  id  Required parameter: The license ID of the item to (re)download. The download
     *         links in the response are valid for 8 hours.
     * @param  body  Required parameter: Information about the videos to redownload
     * @return    Returns the Url wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<Url> downloadVideos(
            final String id,
            final RedownloadVideo body) throws ApiException, IOException {
        return prepareDownloadVideosRequest(id, body).execute();
    }

    /**
     * This endpoint redownloads videos that you have already received a license for.
     * @param  id  Required parameter: The license ID of the item to (re)download. The download
     *         links in the response are valid for 8 hours.
     * @param  body  Required parameter: Information about the videos to redownload
     * @return    Returns the Url wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<Url>> downloadVideosAsync(
            final String id,
            final RedownloadVideo body) {
        try {
            return prepareDownloadVideosRequest(id, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for downloadVideos.
     */
    private ApiCall<ApiResponse<Url>, ApiException> prepareDownloadVideosRequest(
            final String id,
            final RedownloadVideo body) {
        return new ApiCall.Builder<ApiResponse<Url>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/licenses/{id}/downloads")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, Url.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint creates one or more collections (clipboxes). To add videos to collections, use
     * `POST /v2/videos/collections/{id}/items`.
     * @param  body  Required parameter: Collection metadata
     * @return    Returns the CollectionCreateResponse wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<CollectionCreateResponse> createVideoCollection(
            final CollectionCreateRequest body) throws ApiException, IOException {
        return prepareCreateVideoCollectionRequest(body).execute();
    }

    /**
     * This endpoint creates one or more collections (clipboxes). To add videos to collections, use
     * `POST /v2/videos/collections/{id}/items`.
     * @param  body  Required parameter: Collection metadata
     * @return    Returns the CollectionCreateResponse wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<CollectionCreateResponse>> createVideoCollectionAsync(
            final CollectionCreateRequest body) {
        try {
            return prepareCreateVideoCollectionRequest(body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for createVideoCollection.
     */
    private ApiCall<ApiResponse<CollectionCreateResponse>, ApiException> prepareCreateVideoCollectionRequest(
            final CollectionCreateRequest body) {
        return new ApiCall.Builder<ApiResponse<CollectionCreateResponse>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, CollectionCreateResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint lists your collections of videos and their basic attributes.
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  embed  Optional parameter: Which sharing information to include in the response, such
     *         as a URL to the collection
     * @return    Returns the CollectionDataList wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<CollectionDataList> getVideoCollectionList(
            final Integer page,
            final Integer perPage,
            final List<Embed> embed) throws ApiException, IOException {
        return prepareGetVideoCollectionListRequest(page, perPage, embed).execute();
    }

    /**
     * This endpoint lists your collections of videos and their basic attributes.
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  embed  Optional parameter: Which sharing information to include in the response, such
     *         as a URL to the collection
     * @return    Returns the CollectionDataList wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<CollectionDataList>> getVideoCollectionListAsync(
            final Integer page,
            final Integer perPage,
            final List<Embed> embed) {
        try {
            return prepareGetVideoCollectionListRequest(page, perPage, embed).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getVideoCollectionList.
     */
    private ApiCall<ApiResponse<CollectionDataList>, ApiException> prepareGetVideoCollectionListRequest(
            final Integer page,
            final Integer perPage,
            final List<Embed> embed) {
        return new ApiCall.Builder<ApiResponse<CollectionDataList>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections")
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("per_page")
                                .value((perPage != null) ? perPage : 100).isRequired(false))
                        .queryParam(param -> param.key("embed")
                                .value(Embed.toValue(embed)).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, CollectionDataList.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint gets more detailed information about a collection, including the timestamp for
     * its creation and the number of videos in it. To get the videos in collections, use GET
     * /v2/videos/collections/{id}/items.
     * @param  id  Required parameter: The ID of the collection to return
     * @param  embed  Optional parameter: Which sharing information to include in the response, such
     *         as a URL to the collection
     * @param  shareCode  Optional parameter: Code to retrieve a shared collection
     * @return    Returns the MCollection wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<MCollection> getVideoCollection(
            final String id,
            final List<Embed> embed,
            final String shareCode) throws ApiException, IOException {
        return prepareGetVideoCollectionRequest(id, embed, shareCode).execute();
    }

    /**
     * This endpoint gets more detailed information about a collection, including the timestamp for
     * its creation and the number of videos in it. To get the videos in collections, use GET
     * /v2/videos/collections/{id}/items.
     * @param  id  Required parameter: The ID of the collection to return
     * @param  embed  Optional parameter: Which sharing information to include in the response, such
     *         as a URL to the collection
     * @param  shareCode  Optional parameter: Code to retrieve a shared collection
     * @return    Returns the MCollection wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<MCollection>> getVideoCollectionAsync(
            final String id,
            final List<Embed> embed,
            final String shareCode) {
        try {
            return prepareGetVideoCollectionRequest(id, embed, shareCode).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getVideoCollection.
     */
    private ApiCall<ApiResponse<MCollection>, ApiException> prepareGetVideoCollectionRequest(
            final String id,
            final List<Embed> embed,
            final String shareCode) {
        return new ApiCall.Builder<ApiResponse<MCollection>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections/{id}")
                        .queryParam(param -> param.key("embed")
                                .value(Embed.toValue(embed)).isRequired(false))
                        .queryParam(param -> param.key("share_code")
                                .value(shareCode).isRequired(false))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, MCollection.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Collection not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint sets a new name for a collection.
     * @param  id  Required parameter: The ID of the collection to rename
     * @param  body  Required parameter: The new name for the collection
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<Void> renameVideoCollection(
            final String id,
            final CollectionUpdateRequest body) throws ApiException, IOException {
        return prepareRenameVideoCollectionRequest(id, body).execute();
    }

    /**
     * This endpoint sets a new name for a collection.
     * @param  id  Required parameter: The ID of the collection to rename
     * @param  body  Required parameter: The new name for the collection
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<Void>> renameVideoCollectionAsync(
            final String id,
            final CollectionUpdateRequest body) {
        try {
            return prepareRenameVideoCollectionRequest(id, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for renameVideoCollection.
     */
    private ApiCall<ApiResponse<Void>, ApiException> prepareRenameVideoCollectionRequest(
            final String id,
            final CollectionUpdateRequest body) {
        return new ApiCall.Builder<ApiResponse<Void>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections/{id}")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Collection not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint deletes a collection.
     * @param  id  Required parameter: The ID of the collection to delete
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<Void> deleteVideoCollection(
            final String id) throws ApiException, IOException {
        return prepareDeleteVideoCollectionRequest(id).execute();
    }

    /**
     * This endpoint deletes a collection.
     * @param  id  Required parameter: The ID of the collection to delete
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<Void>> deleteVideoCollectionAsync(
            final String id) {
        try {
            return prepareDeleteVideoCollectionRequest(id).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleteVideoCollection.
     */
    private ApiCall<ApiResponse<Void>, ApiException> prepareDeleteVideoCollectionRequest(
            final String id) {
        return new ApiCall.Builder<ApiResponse<Void>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections/{id}")
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Collection not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint lists the categories (Shutterstock-assigned genres) that videos can belong to.
     * @param  language  Optional parameter: Language for the keywords and categories in the
     *         response
     * @return    Returns the CategoryDataList wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<CategoryDataList> listVideoCategories(
            final Language language) throws ApiException, IOException {
        return prepareListVideoCategoriesRequest(language).execute();
    }

    /**
     * This endpoint lists the categories (Shutterstock-assigned genres) that videos can belong to.
     * @param  language  Optional parameter: Language for the keywords and categories in the
     *         response
     * @return    Returns the CategoryDataList wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<CategoryDataList>> listVideoCategoriesAsync(
            final Language language) {
        try {
            return prepareListVideoCategoriesRequest(language).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for listVideoCategories.
     */
    private ApiCall<ApiResponse<CategoryDataList>, ApiException> prepareListVideoCategoriesRequest(
            final Language language) {
        return new ApiCall.Builder<ApiResponse<CategoryDataList>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/categories")
                        .queryParam(param -> param.key("language")
                                .value((language != null) ? language.value() : null).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("basic")
                                        .add("customer_accessCode")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, CategoryDataList.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint adds one or more videos to a collection by video IDs.
     * @param  id  Required parameter: The ID of the collection to which items should be added
     * @param  body  Required parameter: Array of video IDs to add to the collection
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<Void> addVideoCollectionItems(
            final String id,
            final CollectionItemRequest body) throws ApiException, IOException {
        return prepareAddVideoCollectionItemsRequest(id, body).execute();
    }

    /**
     * This endpoint adds one or more videos to a collection by video IDs.
     * @param  id  Required parameter: The ID of the collection to which items should be added
     * @param  body  Required parameter: Array of video IDs to add to the collection
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<Void>> addVideoCollectionItemsAsync(
            final String id,
            final CollectionItemRequest body) {
        try {
            return prepareAddVideoCollectionItemsRequest(id, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for addVideoCollectionItems.
     */
    private ApiCall<ApiResponse<Void>, ApiException> prepareAddVideoCollectionItemsRequest(
            final String id,
            final CollectionItemRequest body) {
        return new ApiCall.Builder<ApiResponse<Void>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections/{id}/items")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Collection not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint lists the IDs of videos in a collection and the date that each was added.
     * @param  id  Required parameter: Collection ID
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  shareCode  Optional parameter: Code to retrieve the contents of a shared collection
     * @param  sort  Optional parameter: Sort order
     * @return    Returns the CollectionItemDataList wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<CollectionItemDataList> getVideoCollectionItems(
            final String id,
            final Integer page,
            final Integer perPage,
            final String shareCode,
            final Sort5 sort) throws ApiException, IOException {
        return prepareGetVideoCollectionItemsRequest(id, page, perPage, shareCode, sort).execute();
    }

    /**
     * This endpoint lists the IDs of videos in a collection and the date that each was added.
     * @param  id  Required parameter: Collection ID
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  shareCode  Optional parameter: Code to retrieve the contents of a shared collection
     * @param  sort  Optional parameter: Sort order
     * @return    Returns the CollectionItemDataList wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<CollectionItemDataList>> getVideoCollectionItemsAsync(
            final String id,
            final Integer page,
            final Integer perPage,
            final String shareCode,
            final Sort5 sort) {
        try {
            return prepareGetVideoCollectionItemsRequest(id, page, perPage, shareCode, sort).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getVideoCollectionItems.
     */
    private ApiCall<ApiResponse<CollectionItemDataList>, ApiException> prepareGetVideoCollectionItemsRequest(
            final String id,
            final Integer page,
            final Integer perPage,
            final String shareCode,
            final Sort5 sort) {
        return new ApiCall.Builder<ApiResponse<CollectionItemDataList>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections/{id}/items")
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("per_page")
                                .value((perPage != null) ? perPage : 100).isRequired(false))
                        .queryParam(param -> param.key("share_code")
                                .value(shareCode).isRequired(false))
                        .queryParam(param -> param.key("sort")
                                .value((sort != null) ? sort.value() : "oldest").isRequired(false))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, CollectionItemDataList.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Collection not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint removes one or more videos from a collection.
     * @param  id  Required parameter: The ID of the Collection from which items will be deleted
     * @param  itemId  Optional parameter: One or more video IDs to remove from the collection
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<Void> deleteVideoCollectionItems(
            final String id,
            final List<String> itemId) throws ApiException, IOException {
        return prepareDeleteVideoCollectionItemsRequest(id, itemId).execute();
    }

    /**
     * This endpoint removes one or more videos from a collection.
     * @param  id  Required parameter: The ID of the Collection from which items will be deleted
     * @param  itemId  Optional parameter: One or more video IDs to remove from the collection
     * @return    Returns the Void wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<Void>> deleteVideoCollectionItemsAsync(
            final String id,
            final List<String> itemId) {
        try {
            return prepareDeleteVideoCollectionItemsRequest(id, itemId).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleteVideoCollectionItems.
     */
    private ApiCall<ApiResponse<Void>, ApiException> prepareDeleteVideoCollectionItemsRequest(
            final String id,
            final List<String> itemId) {
        return new ApiCall.Builder<ApiResponse<Void>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/collections/{id}/items")
                        .queryParam(param -> param.key("item_id")
                                .value(itemId).isRequired(false))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .withAuth(auth -> auth
                                .add("customer_accessCode"))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("Collection not found",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint searches for videos that are similar to a video that you specify.
     * @param  id  Required parameter: The ID of a video for which similar videos should be returned
     * @param  language  Optional parameter: Language for the keywords and categories in the
     *         response
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @return    Returns the VideoSearchResults wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<VideoSearchResults> findSimilarVideos(
            final String id,
            final Language language,
            final Integer page,
            final Integer perPage,
            final View2 view) throws ApiException, IOException {
        return prepareFindSimilarVideosRequest(id, language, page, perPage, view).execute();
    }

    /**
     * This endpoint searches for videos that are similar to a video that you specify.
     * @param  id  Required parameter: The ID of a video for which similar videos should be returned
     * @param  language  Optional parameter: Language for the keywords and categories in the
     *         response
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  view  Optional parameter: Amount of detail to render in the response
     * @return    Returns the VideoSearchResults wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<VideoSearchResults>> findSimilarVideosAsync(
            final String id,
            final Language language,
            final Integer page,
            final Integer perPage,
            final View2 view) {
        try {
            return prepareFindSimilarVideosRequest(id, language, page, perPage, view).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for findSimilarVideos.
     */
    private ApiCall<ApiResponse<VideoSearchResults>, ApiException> prepareFindSimilarVideosRequest(
            final String id,
            final Language language,
            final Integer page,
            final Integer perPage,
            final View2 view) {
        return new ApiCall.Builder<ApiResponse<VideoSearchResults>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/{id}/similar")
                        .queryParam(param -> param.key("language")
                                .value((language != null) ? language.value() : null).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("per_page")
                                .value((perPage != null) ? perPage : 20).isRequired(false))
                        .queryParam(param -> param.key("view")
                                .value((view != null) ? view.value() : "minimal").isRequired(false))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("basic")
                                        .add("customer_accessCode")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, VideoSearchResults.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Forbidden",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint lists videos that have been updated in the specified time period to update
     * content management systems (CMS) or digital asset management (DAM) systems. In most cases,
     * use the `interval` parameter to show videos that were updated recently, but you can also use
     * the `start_date` and `end_date` parameters to specify a range of no more than three days. Do
     * not use the `interval` parameter with either `start_date` or `end_date`.
     * @param  startDate  Optional parameter: Show videos updated on or after the specified date.
     *         The API will default to UTC (00:00:00) if no specific time is provided, ensuring
     *         consistency.
     * @param  endDate  Optional parameter: Show videos updated before the specified date. The API
     *         will default to UTC (00:00:00) if no specific time is provided, ensuring consistency.
     *         Please note that the end date must be at least 5 minutes after the start date.
     * @param  interval  Optional parameter: Show videos updated in the specified time period, where
     *         the time period is an interval (like SQL INTERVAL) such as 1 DAY, 6 HOUR, or 30
     *         MINUTE; the default is 1 HOUR, which shows videos that were updated in the hour
     *         preceding the request
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  sort  Optional parameter: Sort by oldest or newest videos first
     * @return    Returns the UpdatedMediaDataList wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<UpdatedMediaDataList> getUpdatedVideos(
            final String startDate,
            final String endDate,
            final String interval,
            final Integer page,
            final Integer perPage,
            final Sort5 sort) throws ApiException, IOException {
        return prepareGetUpdatedVideosRequest(startDate, endDate, interval, page, perPage,
                sort).execute();
    }

    /**
     * This endpoint lists videos that have been updated in the specified time period to update
     * content management systems (CMS) or digital asset management (DAM) systems. In most cases,
     * use the `interval` parameter to show videos that were updated recently, but you can also use
     * the `start_date` and `end_date` parameters to specify a range of no more than three days. Do
     * not use the `interval` parameter with either `start_date` or `end_date`.
     * @param  startDate  Optional parameter: Show videos updated on or after the specified date.
     *         The API will default to UTC (00:00:00) if no specific time is provided, ensuring
     *         consistency.
     * @param  endDate  Optional parameter: Show videos updated before the specified date. The API
     *         will default to UTC (00:00:00) if no specific time is provided, ensuring consistency.
     *         Please note that the end date must be at least 5 minutes after the start date.
     * @param  interval  Optional parameter: Show videos updated in the specified time period, where
     *         the time period is an interval (like SQL INTERVAL) such as 1 DAY, 6 HOUR, or 30
     *         MINUTE; the default is 1 HOUR, which shows videos that were updated in the hour
     *         preceding the request
     * @param  page  Optional parameter: Page number
     * @param  perPage  Optional parameter: Number of results per page
     * @param  sort  Optional parameter: Sort by oldest or newest videos first
     * @return    Returns the UpdatedMediaDataList wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<UpdatedMediaDataList>> getUpdatedVideosAsync(
            final String startDate,
            final String endDate,
            final String interval,
            final Integer page,
            final Integer perPage,
            final Sort5 sort) {
        try {
            return prepareGetUpdatedVideosRequest(startDate, endDate, interval, page, perPage,
            sort).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getUpdatedVideos.
     */
    private ApiCall<ApiResponse<UpdatedMediaDataList>, ApiException> prepareGetUpdatedVideosRequest(
            final String startDate,
            final String endDate,
            final String interval,
            final Integer page,
            final Integer perPage,
            final Sort5 sort) {
        return new ApiCall.Builder<ApiResponse<UpdatedMediaDataList>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v2/videos/updated")
                        .queryParam(param -> param.key("start_date")
                                .value(startDate).isRequired(false))
                        .queryParam(param -> param.key("end_date")
                                .value(endDate).isRequired(false))
                        .queryParam(param -> param.key("interval")
                                .value((interval != null) ? interval : "1 HOUR").isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("per_page")
                                .value((perPage != null) ? perPage : 100).isRequired(false))
                        .queryParam(param -> param.key("sort")
                                .value((sort != null) ? sort.value() : "newest").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("basic")
                                        .add("customer_accessCode")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, UpdatedMediaDataList.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}